### ISSUE TITLE
Frequent Issue Detection

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#100]
At the moment we recommend users to disable frequent issue detection here:
https://keptn.sh/docs/0.6.0/reference/monitoring/dynatrace/#disable-frequent-issue-detection

There is an API that can do that for us: https://www.dynatrace.com/support/help/extend-dynatrace/dynatrace-api/configuration-api/frequent-issue-detection-api/

When executing `keptn configure monitoring dynatrace` we can either
* check the current configuration and warn the user that frequent issue detection is turned off
* automatically set it to our desired configuration (turn off frequent issue detection) - I am not sure if this is the desired behaviour as this modification is applied for the whole tenant, not just for the Keptn specific things.

**Comment by arthurpitman** [comment]
Closing this as it will be addressed as part of our support for dynatrace-monitoring-as-code to be implemented in #237
