### ISSUE TITLE
Configure Monitoring for Dynatrace should configure k8s Monitoring

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#112]
Right now keptn configure monitoring dynatrace installs the OneAgent, creates tags, management zones and dashboards.
One of our users gave us feedback that it should additionally setup Kubernetes Monitoring by using the kubernetes configuration API of Dynatrace. This would automate an additional step

FYI - ported this over from here: https://github.com/keptn/keptn/issues/1524

**Comment by agrimmer** [comment]
This type of use case will be supported by Monaco (see #237 for details).
