### ISSUE TITLE
Workaround for wrong alerting profiles in Dynatrace-Service 0.6.2

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#125]
We noticed a problem of not retrieving all problem notifications in version 0.6.2 of the Dynatrace-Service. The alerting profile *Keptn* is automatically configured to have an event-filter for the event title.

While we are fixing this issue within our code-base (see Issue #122 and PR #124), we are providing a workaround for this by manually editing the profile in the Dynatrace UI.

1. Log in to your Dynatrace Tenant.
2. Navigate to Settings.
3. Within settings, navigate to Alerting Profiles:
4. Edit the alerting profile *Keptn* and delete the event filter *Custom: Where Title contains 'Keptn'*.

![Screenshot from 2020-04-09 09-51-04](https://user-images.githubusercontent.com/56065213/78871381-e6b35300-7a47-11ea-893a-1cbe576dd07d.png)

**Comment by arthurpitman** [comment]
As Dynatrace-Service 0.6.2 is no longer being supported, I will close this issue.
