### ISSUE TITLE
Process problem event with source `dynatrace`

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-service#127]
If a problem event is received by the dynatrace-service, it checks whether the source is equals `https://github.com/keptn/keptn/api`: 
https://github.com/keptn-contrib/dynatrace-service/blob/master/pkg/event_handler/problem_handler.go#L58

Due to the change in https://github.com/keptn/keptn/pull/1653/files, the event source is not `https://github.com/keptn/keptn/api` per default, but rather the real source of the event, i.e., dynatrace.

![image](https://user-images.githubusercontent.com/729071/79740818-91f1c100-8300-11ea-90ac-d3981bd8015f.png)

**Definition of Done:** 
- [ ] dynatrace-service processes problem events with source: `dynatrace`.

**Comment by christian-kreuzberger-dtx** [comment]
Make sure to also double-check the events subscribed to in the distributor

**Comment by christian-kreuzberger-dtx** [comment]
@bacherfl I believe this has been fixed by your PR #129 and we can close this, correct?
