### ISSUE TITLE
Handle events from other services

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn-contrib/dynatrace-service#131]
As discussed here - https://github.com/keptn-sandbox/jira-service/issues/6 - I'd like the ability for this service to act like as an API for other services.

My third party service can then send a payload to the `dynatrace-service` and the `dynatrace-service` is then responsible for sending the event to Dynatrace.

This makes third party service creation easier as authors don't have to reinvent the wheel for every new service.

**Comment by christian-kreuzberger-dtx** [comment]
To be discussed: Direct communication between jira-service and dynatrace-service vs. jira-service sends a cloud-event (e.g., sh.keptn.events.comment) and dynatrace-service reacts on that event.

**Comment by Dynatrace-Adam-Gardner** [comment]
Did this discussion get anywhere @christian-kreuzberger-dtx ? I'm updating the JIRA service for 0.8.* and this has come back into focus. It's be nice to distribute an event (sh.keptn.dynatrace-service.triggered) with a payload that sends a custom info event to Dynatrace.

**Comment by arthurpitman** [comment]
@Dynatrace-Adam-Gardner, this is a great enhancement - it is easy to see the benefit. Nevertheless, as this enhancement will require significant effort, we will have to delay implementation for the next couple of sprints.

**Comment by arthurpitman** [comment]
Closing this for now.
