### ISSUE TITLE
Overwrite alerting profile if it already exists

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#134]
As a follow-up on issue #122 and #125, we need to overwrite the alerting profile in case it already exists.

Else the user still has to apply the work-around specified in #125.

**Comment by agrimmer** [comment]
Going forward, the configuration of the Dynatrace Tenant (including the alerting profile) will be done via Monaco. Therefore, the user will get the full control what alerting profile he/she would like to have.
