### ISSUE TITLE
Use k8s ServiceAccount with a restricted set of permissions instead of default

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#147]
Currently, the service uses the `default` Service Account with a set of high privileges inside the k8s clusters.

Use a dedicated service account with a minimum set of privileges as described in our contributing guidelines here https://github.com/keptn-sandbox/contributing/pull/2

This has been partially introduced by @thschue in https://github.com/keptn-contrib/dynatrace-service/pull/146, but I think we also need to consider that dynatrace-service needs read-access to several secrets, as detailed in https://github.com/keptn-contrib/dynatrace-sli-service/issues/58

**Definition of Done**:
- Service either uses the `keptn-default` Service Account which has no privileges at all or a new, dedicated Service Account with a minimal set of permissions

**Comment by agrimmer** [comment]
Thanks for the issue, but I think this is already implemented with the role
https://github.com/keptn-contrib/dynatrace-service/blob/6ba9aed1fa0f65b9f4599bb5ee27a72e98fb20d6/deploy/manifests/dynatrace-service/dynatrace-service.yaml#L20
@thschue Please correct me if I am wrong.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks, didn't see that.

So we need to introduce a similar role in dynatrace-sli-service
