### ISSUE TITLE
Dynatrace Keptn Dashboard Improvements

### ISSUE THREAD

**Issue by agrimmer** [keptn-contrib/dynatrace-service#153]
The "keptn configure monitoring dynatrace" is a great way to enable automatic generation of dashboards. Here a couple of improvements I would like to see

1: Use label "Services in dev", "Services in prod" for the headers where you list the links to the onboarded services
2: Filter the infrastructure tiles on top with the hosts that actually run this keptn instance. This probably requires you to install the OneAGent operator with a dedicated HOST_GROUP property that indicates the keptn installation name, e.g: "keptn k8s pre-prod" - with that you can then filter these tiles based on host group name
3: The section name "Operations" doesn't make sense when it just shows the link to the keptns bridge. I would simply call the section "Keptn" and change the link to "Open Bridge"
4: I would add a Disk and Memory Tile to the "Infrastructure" section as the dashboard then includes all major resources: cpu, network, disk, memory. Or consider
5: Add a section called "Environment Availability" - this would show synthetic tests that are testing the availability of services deployed in each stage

Following is a screenshot that includes my suggestions
![73251114-98b4e000-41b8-11ea-9223-a5643554ebe0](https://user-images.githubusercontent.com/10980861/87134869-8e376000-c299-11ea-94d7-a7ae97de1d2e.png)

**Comment by agrimmer** [comment]
Moved https://github.com/keptn/keptn/issues/1329 to this repo.

**Comment by arthurpitman** [comment]
This type of use case will be supported by Monaco (see #237 for details)
