### ISSUE TITLE
Consistency in creating dynatrace secret

### ISSUE THREAD

**Issue by kristofre** [keptn-contrib/dynatrace-service#170]
When creating the Dynatrace secret, we need to specify 3 endpoints:
- Dynatrace tenant
- Keptn api
- Keptn bridge (optional)

Dynatrace tenant is without https but keptn api and bridge include the protocol.
This is very confusing for the end-user and cause easy mistakes which are not always noticed by the user unless logs are inspected. Also when copying the Dynatrace tenant url from the browser it includes the protocol.

Suggestion is to always allow the protocol, also for Dynatrace and also handle the situation better where a trailing slash gets added by mistake.

**Comment by arthurpitman** [comment]
@kristofre I will investigate this issue

**Comment by arthurpitman** [comment]
Closing this as already fixed
