### ISSUE TITLE
Add support for Remediation triggered & Action finished events

### ISSUE THREAD

**Issue by alipatton10** [keptn-contrib/dynatrace-service#174]
Can we add support for these events where:
* `remediation.triggered` would send a **Custom info** event, and
* `action.finished` - if successful - would send a **Configuration changed** event to Dynatrace: (this is implemented in PR: #177)

![image](https://user-images.githubusercontent.com/729071/99356596-b586e500-28aa-11eb-8a48-d71f807ae5d6.png)

That way in Dynatrace we can see that self-healing was what remediated the issue. I think it is also important that we find a way for Keptn to send a configuration changed event from the unleash server but I guess that is a different topic.

**Comment by arthurpitman** [comment]
Fixed in #177
