### ISSUE TITLE
Polling for new Services based on DT-tags

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-service#191]
**Note:** Please consider the comment: https://github.com/keptn-contrib/dynatrace-service/issues/191#issuecomment-698275605

---
As a Dynatrace user, I would like to tag my Service in Dynatrace to automatically create the Keptn entities, or to add a service to a project. 

**Status quo:**

A Keptn managed service has the tags: `keptn_project`, `keptn_stage`, and `keptn_service`

![image](https://user-images.githubusercontent.com/729071/93744558-54b49680-fbf2-11ea-8842-4e433524c6d2.png)

**Assumption:**
- A service must have the tags: `keptn_project`, `keptn_stage`, and `keptn_service` --> this set is unique. 
- It is not supported to add the tag of an already available project but with another stage. (project update with a new stage is not supported) (i.e.: project and stage are the primary key) 

**Task**
- Add a watchdog that periodically checks if there is a service with a new unique set of tags. 
- The time interval is configurable (since we can assume that not every 2 minutes a new service/project shows up) 
- If a new unique set of tags is detected, check if the **project with this stage** already exists:
  - yes: add service: `keptn create service xyz --project=abc`
  - no: does the **project** already exist? 
     - yes: an update of a project is not supported. (log info message) (_remark_: then the stage is new. > this is not supported)
     - no: (1) create shipyard, (2) create project, and (3) create service

**Definition of Done:**
- [ ] If a service is tagged, after, e.g. 1min a Keptn service is created

**Comment by christian-kreuzberger-dtx** [comment]
I can see some challenges that we need to discuss.

1. I'm not sure whether there is an endpoint right now that allows us to query all tags on all services (I believe there is none, one would have to query all services and process the tags on them, but feel free to correct me). Also I believe there is no way to automatically detect "new tags" on services. We need to store the API result, and compare it every x minutes. This is inefficient and definately not something that should run forever. **I'll investigate on that though**
1. Why is the use-case only focused on services? What if a user wants to monitor other entities, such as hosts, workloads, process groups, monitors, custom devices?
1. What if the specified tags are inconsistent? E.g., how do we handle having different services per stage?
   * `service1`: `keptn_project: abc`, `keptn_stage: dev`, `keptn_service: service1`
   * `service2`: `keptn_project: abc`, `keptn_stage: prod`, `keptn_service: foobar`
1. What if we create a project/service/stage based on that information, but the user was not done creating the tags?
1. How do we handle cases where we have installed Keptn, onboarded a project with a shipyard, several services, ..., and they are running in Kubernetes, monitored by OneAgent. Now we uninstall Keptn, and install it again. Will those projects/stages/services automatically be detected? What shipyard will we use?
1. How do we order stages in the shipyard file? Alphabetically? By creation-date?
1. This form of service creation does not allow the user to configure the shipyard file at all. We currently do not support updating the shipyard file either. I see a strong dependency in being able to update the shipyard file before we can offer such a functionality.

**Comment by christian-kreuzberger-dtx** [comment]
Ad 1) I've looked at the REST API (Dynatrace Environment API 2.0), and there is an early adopters endpoint `/api/v2/tags`, which we can query using `entitySelector=type(SERVICE)` and which would return something like this in my example:
```
{
  "totalCount": 3,
  "tags": [
    {
      "context": "CONTEXTLESS",
      "key": "keptn_service: catalogue",
      "stringRepresentation": "keptn_service: catalogue"
    },
    {
      "context": "CONTEXTLESS",
      "key": "keptn_stage: hardening",
      "stringRepresentation": "keptn_stage: hardening"
    },
    {
      "context": "CONTEXTLESS",
      "key": "keptn_project: musicshop",
      "stringRepresentation": "keptn_project: musicshop"
    }
  ]
}
```

Important info on that endpoint:
```
You need to set one of these criteria:

    * Entity type: type("value").
    * Dynatrace entity ID: entityId("id"). You can specify several IDs, separated by a comma (entityId("id-1","id-2")).
```
Also:
```
Required Api-Token scope:
entities.read (Read entities using API V2)
```

So we can only query one type per API call (which results in many calls if we want to support hosts, applications, ...).

Also, this does not tell us if any of the services currently active use the tags, it only tells us that those tags should be present somewhere.

**Comment by agrimmer** [comment]
I see another challenge:
- For example, let's assume a customer deletes an automatically created Keptn project/service but does not remove the tags in Dynatrace. Is the Keptn project/service then re-created by the watchdog?

**Comment by agrimmer** [comment]
Furthermore, I think that checking all tags and generating Keptn entities should not run periodically in the background. I think that this should be an action triggered by the user, e.g. with `keptn configure monitoring dynatrace`.

**Comment by johannes-b** [comment]
Thanks for your thoughts!! They all address a valid point/concern. I will come up with a refinement of the user-story, as the idea of implementing periodic sync is maybe too much future looking.

**Comment by johannes-b** [comment]
Again, many thanks for everybody's thoughts! I will not edit the original description of the issue, but rather provide an update here: 

---

**Requirement:** Keptn has a default project “Dynatrace” with a one-stage shipyard: “quality-gate”

**User Story:**
- In Dynatrace, I tag my Service with the tags: `keptn_managed`+ `keptn_service: <serviceName>`
- The dynatrace-service looks every 5min (interval is configurable) if there is a new Dynatrace Service with the tags `keptn_managed`+ `keptn_service` 
- If a new Dynatrace service is detected, the dynatrace-service creates a new (Keptn) service and adds it to the Keptn project “Dynatrace” + it adds a default SLO.yaml file (Response time, Failure rate, CPU, Throughput) for this service. 
  - Automation of: 
    - `keptn create service “xyz” --project=Dynatrace`
    - `keptn add-resource --resource=slo.yaml`
- _Fallback for invalid service name:_ If the tag `keptn_service` contains a not valid name (i.e., no valid folder name, e.g.: `keptn_service: carts:12/987`), the fallback is to the event-id, e.g.: SERVICE-F88B4D0485F54D09 (Without this fallback, Keptn cannot create a service and the user would never know why it did not work.)

**Scope of the Feature:** 
- This feature supports tags on Services
- The value of keptn_service must be a valid folder name (fallback to entity-id)
- Services are added to the Keptn project: “Dynatrace”
- A default SLO (Response time, Failure rate, CPU, Throughput) is added to the service

**Example:**
![image](https://user-images.githubusercontent.com/729071/94137462-b7ae6380-fe66-11ea-85d4-355c53b1bfa3.png)

**Comment by johannes-b** [comment]
As an example, the following CURL returns services with the `keptn_project` tag: 

```
curl -X GET "https://tno85405.live.dynatrace.com/api/v2/entities?entitySelector=type%28%22SERVICE%22%29%2Ctag%28%22keptn_project%3Amusicshop%22%29" -H "accept: application/json; charset=utf-8" -H "Authorization: Api-Token "
```
