### ISSUE TITLE
When Dynatrace problem is closed it does not always lead to a closure of that problem in Keptn

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#222]
It seems that when Dynatrace automatically closes a problem this information is not sent over to Keptn which means the problem in keptn is never closed.
When the problem gets closed manually in Dynatrace, e.g: via the API or the UI - then Keptn receives the problem closed event.

It should be irrelevant how the Dynatrace problem gets closed - in any case the problem state should be reflected in keptn so that the keptn remediaiton workflow is also marked as completed

**Comment by arthurpitman** [comment]
@grabnerandi, is this still relevant?
