### ISSUE TITLE
Troubleshooting issues with Problem Event Handling is hard due to lack of good logs

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#223]
Currently there is not a whole lot of log output when the dynatrace-service is processing incoming problem events from Dynatrace.
In order to troubleshoot or analyze problems that are sent to Keptn it would be a minimum requirement to see PID & Problem Status in the log output when the dynatrace-service receives an event from Dynatrace

**Comment by arthurpitman** [comment]
Closing this as it will be addressed on a general level for all event handlers.
