### ISSUE TITLE
Adapt Problem event payload to use structs compatible with Keptn 0.8

### ISSUE THREAD

**Issue by bacherfl** [keptn-contrib/dynatrace-service#224]
In this [PR](https://github.com/keptn/go-utils/pull/229) we have removed several outdated structs that implemented the spec verion 0.1.7 of Keptn. Some of those are still referenced (e.g. the Problem events). These have to be replaced by their spec v0.2.0 equivalents

**Comment by arthurpitman** [comment]
@bacherfl, is this still relevant?

**Comment by arthurpitman** [comment]
Let's investigate this when we rework problem remediation.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
