### ISSUE TITLE
Dynatrace Service Synchronization must also work with Environment Tags

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#227]
The Dynatrace Service has a great feature for synchronizing dynatrace monitored services with the dynatrace keptn project. To make this work the Dynatrace Service polls the Dynatrace Smartscape API and queries for entities with the tags "keptn_managed" and "keptn_service:SERVICENAME". 
Right now it seems it only supports "[CONTEXTLESS]keptn_service:SERVICENAME" but not "[Environment]keptn_service:SERVICENAME".

The query is defined here:
https://github.com/keptn-contrib/dynatrace-service/blob/4bed3c2ff45c1ba6c1b0c87cb65bba91a58b6bbc/pkg/lib/service_sync.go#L347

The differnece between the two CONTEXTS is that one comes in through an auto-tagging rule the other one through the DT_TAGS environment variable. Both are very commonly used options to define tags which is why the dynatrace-service should support both.

The current implementation can be found here where the service queries the entities matching the tag: https://github.com/keptn-contrib/dynatrace-service/blob/4bed3c2ff45c1ba6c1b0c87cb65bba91a58b6bbc/pkg/lib/service_sync.go#L332-L342 - it has to be extended to also include the ENVIRONMENT tags

**Comment by arthurpitman** [comment]
I'll take this issue
