### ISSUE TITLE
Default SLI metric for error_rate is actually failed request count and not error rate

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#229]
This is the same as the issue for the dynatrace-sli-service: https://github.com/keptn-contrib/dynatrace-sli-service/issues/128
The dynatrace-service has one reference to the error rate SLI but uses `builtin:service.errors.total.count` instead of the true rate metric which is `builtin:service.errors.total.rate` 

This is an easy fix in
* metrics_events.go:getTimeseriesConfig
* readme.md

**Comment by arthurpitman** [comment]
Fixed in #269
