### ISSUE TITLE
Use Monaco to create Dynatrace Configuration instead of hard-coded API calls

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#237]
Right now the Dynatrace-Service makes several configuration changes when a new keptn project is created or when you call "Keptn configure monitoring", e.g: dashboards get created, tagging rules configured, ...

Instead of hard coding these API calls it would be better to leverage Dynatrace's Open Source Project [Monaco](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code) to apply this configuration. 

Here are some thoughts on how that could look like
1. Move the handing of the "configure monitoring" event to the monaco service
2. Let the monaco service handling "configure monitoring" and pull the configuration from Keptn's configuration repo on project level
3. If there is no monaco configuration in the config repo the monaco-service can provide the current configuration (dashboard, tagging rules ...) as defaults. It should not only apply those default but also upload them to the configuration repo so that a subsequent configure monitoring would take it from there
4. Provide best practice guidance or templates when creating a new keptn project and explain users how to upload their own monaco configuration to the Keptn's configuration Repo when creating a new project. That allows user to be better in control about which configuration to happen when configuring monitoring support for dynatrace

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
