### ISSUE TITLE
Better handling of Dynatrace Test Notification Message when setting up Remediation Integration

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#238]
When setting up the Integration between Dynatrace and Keptn by configuring a Dynatrace Problem Notification integration it is mandatory to first send a "Test Notification" before storing that configuration. 
Also - when making changes to the configuration, e.g: changing the token, endpoint, alerting profile, payload ... Dynatrace requires you to send a new test notification to confirm the settings work correctly.

Such a Test Notification uses some dummy data such as 99999 for PID or 999 for ProblemID. As the default Keptn Payload as described in the doc also uses the {PID} placeholder for the Keptn Context ID all test notification events sent to Keptn will end up under the same Keptn Context which makes it very hard to validate if the message actually arrived on Keptns side and was assigned to the correct project, service and stage as you have to first find the first problem open event for that test PID and then scroll down to see whether the latest test notification came in correctly.

The other problem is that - even though this is just a "Test Event" - Keptn will trigger the full remediation workflow. This is just soemthing that should be made clear in the documentation. Another option to solve this is to handle the PID 99999 specially and not trigger the remediation workflow - but that would then be something that has to be handled by the Remediaiton Service and not hte Dynatrace-Service

**Comment by grabnerandi** [comment]
The easiest fix of this problem is actually in the readmes that explain how to setup problem notifications. I found two instances so far but there might be more
1: readme.md of dynatrace-service
2: readme.md for the keptnonk3s for Dynatrace

in both cases the JSON Payload for the Problem Notification Integration should remove setting shkeptncontext and id as shown below
```
   ""shkeptncontext":"{PID}",
  ...
  "id":"{PID}",
   ...
```

This will make sure that the incoming event always gets a unique keptn context and therefore doesnt merge all of the test notifications together into a single keptn context

**Comment by grabnerandi** [comment]
Another fix might be in pkg\lib\dynatrace_api.models.go - const PROBLEM_NOTIFICATION_PAYLOAD
This constant is used when handling "keptn configure monitoring" to setup the problem notification. While this works in general - itw ill run into the same problem as explained above. If a user tries to edit that notification integration every "Send Test Notification" will use the same Keptn Context becuase the default value for {PID} during te test event is 99999 which translates into the keptncontext UUID - 39393939-3920-4020-a020-202020202020

**Comment by grabnerandi** [comment]
In discussion with @bacherfl I learned that using "{PID}" as default value for keptncontext was done on-purpose so that we can automatically map problem open and problem close without having to do a look up for the inital problem open
That means that we should then handle the special UUID "39393939-3920-4020-a020-202020202020" separately. For this UUID we will only every get the problem open but never a problem close as the Test Notification only sends out problem open events. 
So - the proposal therefore is to handle that incoming UUID in the dynatrace-service and simply create a unique UUID instead of this one

**Comment by arthurpitman** [comment]
#237 is a prerequisite

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
