### ISSUE TITLE
Dynatrace Events should be sent to PGIs by default and not SERVICES

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#240]
The Dynatrace-Service sends several events to Dynatrace, e.g: Deployment, Test Start / Stop ...
By default those are sent to a SERVICE with the keptn tags attached. This behavior can be changed by defining the attachRules in dynatrace.conf.yaml

As the new Release Inventory screen in Dynatrace - which gives an overview of all deployed components (PGIs) and their respective versions, envionrments and applications focuses on PGIs and not on Services - we should change the default behavior of the dynatrace-service to send events to PGIs instead of SERVICES

Whats the impact?
1: Events sent to PGIs will be included in the Releases screen
2: Events sent to PGIs will also be shown in the services screens in Dynatrace -> so - we have the same behavior as before

As in most cases Keptn deploys containers or processes with meta data such as keptn project, service and stage being passed as Environment Variables - those are picked up by Dynatrace anyway on the PGI level. This is why events should also be sent to the PGI

**Comment by arthurpitman** [comment]
PGI = Process Group Instance

**Comment by arthurpitman** [comment]
@grabnerandi, would it better to send it to both SERVICES and PGIs?
