### ISSUE TITLE
Create a Helm Chart for installing dynatrace-service instead of Kubernetes deployment manifests

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#261]
As described in https://github.com/keptn-contrib/dynatrace-service/issues/260, we have two Kubernetes manifests with multiple Environment Variables in it.

In #260 we also describe a problem that occurs with having multiple manifest files.

To counter this problem, I propose to introduce a helm chart for installing Dynatrace-Service.

This helm chart should have all Environment Variables provided as Values.

# Definition of Done

- [ ] Make sure that skaffold works with the provided Helm Chart (see solution: https://github.com/keptn/keptn/issues/3421) 
- [ ] Helm Chart for Dynatrace-Service with respective values provided
- [ ] README updated with usage examples
- [ ] When releasing a new version, the helm chart needs to be an asset of the release (automation?)
- [ ] Tutorials on tutorials.keptn.sh updated with new install instructions

**Comment by agrimmer** [comment]
Note, please don't delete the manifests in deploy folder! Please only mark them as deprecated.
