### ISSUE TITLE
Determine Root Cause when receiving a problem notification

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-service#279]
**User Story**: 
As a user, I want to be able to map a Dynatrace problem *root cause* to a remediation problem type, so that the correct remediation action for a problem gets executed.

**Details**:
* When the *DynatraceService*  receives a `sh.keptn.events.problem` event, it shall determine the **root cause** by calling the `/problems` endpoint of the Dynatrace API *[1]* and pass the root cause along with the `sh.keptn.event.remediation.triggered` event.

**Definition of Done**:
- [ ] Dynatrace root cause can be specified as `problemType` in the `remediations` section of the `remedation.yaml` file
- [ ] `sh.keptn.event.<stage>.remediation.triggered` event sent by the *DynatraceService* contains the `rootCause` field in the `problem` section
- [ ] Keptn CloudEvents Spec is updated
- [ ] Keptn example files (`remediation.yaml`) are updated to reference the value of the `rootCause` instead of `problemTitle`

---

[1] How to get the root cause:
- Use the `/problems/{problemId}` endpoint from the Dynatrace API while the `problemid` is contained in the *ProblemDetails* see `id`: 
```
      "ProblemDetails": {
        "displayName": "P-210325",
        "endTime": -1,
        "hasRootCause": true,
        "id": "-7814562899452185567_1617086820000V2",
        "impactLevel": "SERVICE",
        "severityLevel": "ERROR",
        "startTime": 1617087120000,
        "status": "OPEN"
      },
```
- The response contains the `evidence` property which contains the root cause of that problem (`eventType` property): 

```
  "evidenceDetails": {
    "totalCount": 1,
    "details": [
      {
        "evidenceType": "EVENT",
        "displayName": "Failure rate increase",
        "entity": {
          "entityId": {
            "id": "SERVICE-1016B63497E3FEF6",
            "type": "SERVICE"
          },
          "name": "sockshop.carts.production"
        },
        "groupingEntity": null,
        "rootCauseRelevant": true,
        "eventId": "-7814562899452185567_1617086820000",
        "eventType": "FAILURE_RATE_INCREASED",
        "startTime": 1617086820000
      }
    ]
  }
```

**Comment by johannes-b** [comment]
Can we address: https://github.com/keptn-contrib/dynatrace-service/issues/278 with this issue?

**Comment by arthurpitman** [comment]
@johannes-b, @warber, is this still on the prioritized backlog of the core team?

**Comment by warber** [comment]
@arthurpitman it is on our backlog, however not planned to be tackled in the very near future.
Would be great if you could work on this.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
