### ISSUE TITLE
Set event on full timeframe of test instead of the moment of evaluation

### ISSUE THREAD

**Issue by vmasch** [keptn-contrib/dynatrace-service#282]
**Status quo:**
It's possible to set an event at the moment of evaluation.

**Proposal:**
It should be possible to highlight the whole timeframe of loadtests with events (for bidirectional traceability).

**Comment by arthurpitman** [comment]
@vmasch, could you please provide us with some more details of your use case?

**Comment by agrimmer** [comment]
Please feel free to re-open this ticket with more details.
