### ISSUE TITLE
Merge dynatrace-service and dynatrace-sli service

### ISSUE THREAD

**Issue by bacherfl** [keptn-contrib/dynatrace-service#283]
Currently, the retrieval of SLI values from the configured DT tenant is done by the dynatrace-sli-service living in [keptn-contrib/dynatrace-sli-service](https://github.com/keptn-contrib/dynatrace-sli-service).

However, since both the dynatrace-service, as well as the dynatrace-sli-service are always used in combination, both services should be merged into one dynatrace-service that combines the functionality of both services. Also, both services should be refactored to increase maintainability (see https://github.com/keptn-contrib/dynatrace-sli-service/issues/175).

**Definition of Done:**

- [ ] All features of the dynatrace-sli-service are supported by the dynatrace-service
- [ ] Refactoring tasks mentioned in https://github.com/keptn-contrib/dynatrace-sli-service/issues/175 are done

**Comment by arthurpitman** [comment]
Closing this issue as it is superseded by #363. #175 will remain in the backlog and will be handled in future refactoring.
