### ISSUE TITLE
Dynatrace Synchronization too restrictive on keptn_service names and doesnt provide any warning

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#294]
Right now the Synchronization mechanism with Dynatrace Monitored Entities validates looks at the existence of a keptn_service tag but also validates the value of that tag to match a specific RegEx, e.g: only lower case is allowed

The validation of the tag can be found here: https://github.com/keptn-contrib/dynatrace-service/blob/4bed3c2ff45c1ba6c1b0c87cb65bba91a58b6bbc/pkg/lib/service_sync.go#L332-L342

The actual RegEx check is in keptncommon.ValidateKeptnEntityName

For Quality Gate Use Cases there should not be a limitation to e.g: all lower case. There should also not be a length limitation as many dynatrace service names have long names and would therefore always exceed our current length restrictions

If we have to keep these restrictions then we have to make sure the end user is made aware of the fact that the synchronization didnt happen because of e.g: invalid naming convention.

Here are a couple of suggestions to make this better for the end user
a: allow mixed case of service names and remove length restriction -> this should not be a problem because the primary use case is quality gates and therefore we never run into k8s length restrictions as we never would run a deployment with those names
b: provide better log output in the Dynatrace Service and also "highlight" those synchronization errors in the Keptns Bridge
c: send a Dynatrace Info Event back to the Dynatrace Service about the status of the synchronization, e.g: "Synchronization Successful -> here is the link to the Keptns Bridge" - OR - "Synchronization failed because of service name violation"

**Comment by arthurpitman** [comment]
Implemented in #332
