### ISSUE TITLE
Introduce bi-directional linking of synchronized Dynatrace services

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#295]
When synchronizing a Dynatrace Monitored Service Entity with Keptn for the purpose of Quality Gates it is hard to know
a) to which service a keptn service links in Dynatrace
b) to which keptn service a dynatrace service maps

I therefore suggest a better bi-directional integration with direct links. here my suggestions of things we should additionally do when a new service is "synchronized"
a: Push an Info Event to the Dynatrace saying "Keptn now managing this service" -> plus a link back to the Keptns Bridge
b: Additionally to the Event push a Tag on the Dynatrace Entity. The advantage of a tag is that it is more permanent where the event is just there once and wont be visible all the time especially as time passes
c: Provide a link from Keptns Bridge to the Dynatrace Entity -> this could be done through some meta data when creating a new keptn service -> e.g: keptn create service myservice --project=dynatrace --externallink=https://mydynatracenetity

For c) -> this requires a general extension in Keptn to define meta data for a service that is then e.g: displayed in the bridge. Think of it like "labels" but on a service level

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
