### ISSUE TITLE
Migrate dynatrace-service to Dynatrace v2 APIs

### ISSUE THREAD

**Issue by agrimmer** [keptn-contrib/dynatrace-service#296]
Currently, the dynatrace-service uses v1 APIs of Dynatrace, which will get deprecated in the second half of 2021.

Please migrate the APIs to v2. 
This includes API calls in the following use cases:
- Keptn configure monitoring (will be addressed with https://github.com/keptn-contrib/dynatrace-service/issues/237)
- remediation (we send comments on a problem)
- sending events to DT

**Definition of Done**:
- dynatrace-service does not use any DT API which will be depreacted

**Comment by arthurpitman** [comment]
#237 is prerequisite for this

**Comment by agrimmer** [comment]
Closing this ticket as each API migration should be a dedicated ticket.
