### ISSUE TITLE
Bug: Helm chart does not allow repositories starting with numbers

### ISSUE THREAD

**Issue by agrimmer** [keptn-contrib/dynatrace-service#305]
The Helm-chart does not support registries starting with numbers due to the used Json schema/pattern defined here https://github.com/keptn-contrib/dynatrace-service/blob/master/chart/values.schema.json#L60

**Definition of Done**:
- Support registries starting with numbers.

**Comment by christian-kreuzberger-dtx** [comment]
@agrimmer has this already been fixed?

**Comment by arthurpitman** [comment]
Already fixed
