### ISSUE TITLE
Dynatrace secret should not contain Keptn API/TOKEN

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-service#309]
## User Story: 

As a user, I don't want to reference the KEPTN_API_URL/TOKEN when creating the secret for the Dynatrace integration.

Expected behavior: 
```
keptn create secret dynatrace 
--from-literal="DT_TENANT=$DT_TENANT" 
--from-literal="DT_API_TOKEN=$DT_API_TOKEN" 
```

### Details:
The CLI command: 
```
keptn create secret dynatrace 
--from-literal="DT_TENANT=$DT_TENANT" 
--from-literal="DT_API_TOKEN=$DT_API_TOKEN" 
--from-literal="KEPTN_API_URL=$KEPTN_DOMAIN/api" 
--from-literal="KEPTN_API_TOKEN=$KEPTN_API_TOKEN" 
--from-literal="KEPTN_BRIDGE_URL=$KEPTN_DOMAIN/bridge"
```

requires the KEPTN_API_URL, KEPTN_API_TOKEN, BRIDGE_URL. This is information that should be stored by a generic secret in Keptn. 

* When installing Keptn, the secret `keptn-api-creds-for-dt-integration` is created which stores the above-mentioned key-value pairs.
* The dynatrace-service (and dynatrace-sli-service) query the Keptn-related information from the secret `keptn-api-creds-for-dt-integration` while the Dynatrace-related data comes from the `dynatrace` secret as created by the user. 

## Acceptance Criteria
- [ ] (Step 1) As a user, I create the secret: 
```
keptn create secret keptn-api-creds-for-dt-integration 
--from-literal="KEPTN_API_URL=$KEPTN_DOMAIN/api" 
--from-literal="KEPTN_API_TOKEN=$KEPTN_API_TOKEN" 
--from-literal="KEPTN_BRIDGE_URL=$KEPTN_DOMAIN/bridge"
```
- [ ] (Step 2) As a user, I create the secret: 
```
keptn create secret dynatrace 
--from-literal="DT_TENANT=$DT_TENANT" 
--from-literal="DT_API_TOKEN=$DT_API_TOKEN" 
```
- [ ] The behaviour of the Dynatrace integration has not changed. 

## Definition of Done:
- [ ] Secret management in dynatrace-service is adopted
- [ ] RBAC updated to allow accessing secret: `keptn-api-creds-for-dt-integration`
- [ ] Documentation/tutorial/Readme.md is updated
  - [ ] Tutorials: 
    - https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace-08/index.html?index=..%2F..keptn08x#0
    - https://tutorials.keptn.sh/tutorials/keptn-argo-rollouts-dynatrace-08-on-k3s/index.html?index=..%2F..keptn08x#0
    - https://tutorials.keptn.sh/tutorials/keptn-quality-gates-dynatrace-08-on-k3s/index.html?index=..%2F..keptn08x#0
  - [ ] Docu: (https://keptn.sh/docs/0.8.x/monitoring/dynatrace/install/#1-create-a-secret-with-required-credentials
  - [ ] Readme.md

**Comment by arthurpitman** [comment]
Rather than breaking existing configurations, we can make reading the keptn-specific variables, i.e. `KEPTN_API_URL`, `KEPTN_API_TOKEN`, `BRIDGE_URL` optional. If they are not present in the `dynatrace` secret, we should read them from environment variables. This also handles the situation where the dynatrace-service is installed externally in the execution plane.

**Comment by arthurpitman** [comment]
Currently there is still a fallback that reads Keptn credentials from the Dynatrace secret. I will close this ticket as this will be removed in the scope of #557.
