### ISSUE TITLE
Sync mechanism is too restrictive on service names

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-service#310]
## Use case

I would like to add the tag `keptn_service : my_service` to a service in order to import it into Keptn. I expect to get the service `my_service` created. However, the sync fails since `_` is not allowed. 

**Details:**
- The check of the tag value uses `ValidateKeptnEntityName` which is too restrictive: https://github.com/keptn-contrib/dynatrace-service/blob/master/pkg/lib/service_sync.go#L345
- Use the function `ValidateUnixDirectoryName´ instead, which is available in the `go-utils` pkg and also used by the `keptn create service` command. 

## Acceptance criteria
- [ ] I can use the service name `my_service`

**Comment by arthurpitman** [comment]
Close in #332
