### ISSUE TITLE
keptn configure montoring --project sockshop: failed to retrieve services of project sockshop: method GET is not allowed, but [POST] are

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#323]
When executing `keptn configure monitoring --project sockshop`, dynatrace-service fails with 
```
failed to retrieve services of project sockshop: method GET is not allowed, but [POST] are
```

A quick troubleshooting lead to the fact that this is caused by 
https://github.com/keptn-contrib/dynatrace-service/blob/9ce4c1ef5a764c9ef9d98fb9c88d49e66dea102b/pkg/lib/dynatrace.go#L110

This leads to the following code not being executed at all:
https://github.com/keptn-contrib/dynatrace-service/blob/9ce4c1ef5a764c9ef9d98fb9c88d49e66dea102b/pkg/lib/dynatrace.go#L114-L116

Looking at the Keptn CLI, this is how it's done:
```
		servicesHandler := apiutils.NewAuthenticatedServiceHandler(endPoint.String(), apiToken, "x-token", nil, endPoint.Scheme)
               ...
		services, err := servicesHandler.GetAllServices(project.ProjectName, stage.StageName)
```

There is also an unauthenticated service handler that does not require the token, we should use that one.

# Definition of Done

- [ ] Latest version of go-utils is used
- [ ] `keptn configure monitoring --project sockshop` no longer fails

**Comment by aborigene** [comment]
I believe this is still happening. I am just trying this today, and got the exactly same problem on AKS:

keptn configure monitoring dynatrace --project=sockshop --service=carts

ID of Keptn context: 1666c719-1ebe-4c72-9f1f-2d1a43bae86b
failed to retrieve services of project sockshop: method GET is not allowed, but [POST] are

I tried running with -v to get more information about the problem with no success.
