### ISSUE TITLE
Easy argument update (dry-run)

### ISSUE THREAD

**Issue by gabrielprioli** [keptn-contrib/dynatrace-service#324]
The instructions to install the service include the following command on Step 3 (Create a secret with the credentials by executing the following command)

```
kubectl -n keptn create secret generic dynatrace
--from-literal="DT_API_TOKEN=<DT_API_TOKEN>" 
--from-literal="DT_TENANT=<DT_TENANT>" 
--from-literal="KEPTN_API_URL=<KEPTN_API_URL>" 
--from-literal="KEPTN_API_TOKEN=<KEPTN_API_TOKEN>"
-oyaml --dry-run | kubectl replace -f -
```

Executing this with:

- Keptn CLI version: 0.8.2
- Keptn cluster version: 0.8.2

Outputs:

`W0514 19:32:29.015825   30380 helpers.go:553] --dry-run is deprecated and can be replaced with --dry-run=client.`

So I propose to edit the command and use the new argument format `--dry-run=client`

**Comment by gabrielprioli** [comment]
#325

**Comment by johannes-b** [comment]
Closed by: https://github.com/keptn-contrib/dynatrace-service/pull/325
