### ISSUE TITLE
Forward event labels to Dynatrace

### ISSUE THREAD

**Issue by thschue** [keptn-contrib/dynatrace-service#337]
In some cases it might be useful to get the information of event labels also in dynatrace.

As an example, a developer might pass the commit hash of the source and the author as labels to the deployment event. In further consequence, it would be very useful to see exactly this information in dynatrace to have all information in one place.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
