### ISSUE TITLE
Send out a release event after a deployment

### ISSUE THREAD

**Issue by yeahservice** [keptn-contrib/dynatrace-service#342]
Currently the dynatrace-service sends out a deployment event after a successful deployment. It would be useful if it follows up with a release event, so that the released version also shows up in the Dynatrace release inventory (see below).

![image](https://user-images.githubusercontent.com/9437246/122176284-b9043e00-ce84-11eb-8330-18083a000c71.png)

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
