### ISSUE TITLE
Create a problem event for failed tests/evaluations 

### ISSUE THREAD

**Issue by yeahservice** [keptn-contrib/dynatrace-service#344]
Currently there seems to be no information in events received by Dynatrace if the tests failed or were successful.
![image](https://user-images.githubusercontent.com/9437246/122178916-519bbd80-ce87-11eb-81b6-87dfeba76037.png)

In comparison, the event sent out after evaluations contains more information

![image](https://user-images.githubusercontent.com/9437246/122179205-932c6880-ce87-11eb-9cc2-68d5fcca174b.png)

It would be useful if the test event could contain more information (at least if the tests failed or were successful). Also if the test/evaluation failed, it would be nice if it shows up as problem event, so that responsible developers can react on it.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
