### ISSUE TITLE
Use CloudEvents to forward errors to Keptn API

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#353]
With Keptn 0.8.4, integration services can now send error log events to the Keptn API via the distributor. These in turn are visible in the Keptn Bridge. Adding this functionality to the dynatrace-service would support users in keeping track of the state of the integration.

Tasks for each area of the service:

- [x] #510
- [ ] #509

**Comment by arthurpitman** [comment]
Note: to send a `sh.keptn.log.error` event, the `data/integrationid` needs to be set to that of the service

**Comment by j-poecher** [comment]
most of it is done - the rest will be handled with #779
