### ISSUE TITLE
Ensure all run time errors are handled and/or logged and not dropped

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#358]
### Current State:

Error handling is all but standardized. Sometimes they are logged, sometimes not, sometimes they are handled, sometimes they are even ignored.

Also most of the errors are not sub-typed. That means we would not know what to do with that error from an outside perspective (should the error be logged, should it be forwarded to the customer - e.g. via CloudEvents to Keptn Uniform).

#### What do we want to achieve:
 * We would like to have a clear error hierarchy (e.g. internal, dynatrace, keptn) so we would be able to distinguish between errors
 * We would like to fail fast, when some problem occurs and propagate a meaningful error (with context and root cause) to the main routines
 * We would like to centralize the error handling as much as possible (events back to keptn or uniform) with a clear opinion on which error information is for users and which is only for internal usage (logs, etc.)
 * Some of the errors (esp. in the event handlers) are currently being swallowed in the event loop. They should be sent out to Keptn via events

### DOD:
 * errors are created where they happened with a meaningful error message and a reusable type (if applicable), that could be shown to an end user
 * errors are encapsulated in other errors if they need to be propagated - so the problem cause trace should be structurally visible in the error objects
 * errors are logged only once and for consistency with this pattern: `log.WithError(err).Error(...)`
 * no errors are dropped anywhere in the code - they should be handled and/or logged
 * #353

**Comment by j-poecher** [comment]
most of it is done - the rest will be handled with #779
