### ISSUE TITLE
Update docs and SLI to not use :merge(0), but use :splitby() instead (in january 2021)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#371]
I heared that in the metrics API v2 the `:merge(0)` selector should be avoided, and might become deprecated in the future.

As an alternative, we should use `:splitby()` when it is supported (no ETA yet).

# Definition of Done

- [ ] Verify that `:splitby()` does the same as `:merge(0)` in our default cases
- [ ] Update any relevant code
- [ ] Update keptn/examples
- [ ] Update keptn/tutorials
- [ ] Update docs in this repo (make sure to search for all occurances of `:merge(0)`!!!)

**Comment by agrimmer** [comment]
Addressed with https://github.com/keptn-contrib/dynatrace-service/issues/395
