### ISSUE TITLE
Send a status.changed events while waiting for metrics from Dynatrace API

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#374]
With the new Keptn spec 0.2.0-alpha, get-sli can also return a .status.changed event, e.g. `sh.keptn.event.get-sli.status-changed`.

For better debugging/troubleshooting I recommend that we send a status-changed when we are sleeping to wait for a response from Dynatrace: 
https://github.com/keptn-contrib/dynatrace-sli-service/blob/9d6c7e6b09f0046fcb9fd74e98b8d5bbfb6dff2f/cmd/main.go#L126-L136

Maybe we don't send it every 10 seconds, but maybe once in the beginning with a message stating how long we will "wait"?

This change will help users to immediately see that the service is responding and working, but needs to wait on Dynatrace itself.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
