### ISSUE TITLE
Add dynatrace-sli-service user agent string when calling Dynatrace API

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#375]
in order to better track incoming calls from the dynatrace-sli-service all API requests should include a specific user agent string that allows dynatrace to better track incoming calls from keptn, the service and the version.

This also applies to the Dynatrace Service and should probably be aligned across all Keptn Services that make outgoing requests.

Open for discussion on the actual user-agent string, e.g: Keptn;Dynatrace-SLI-Service;0.x.x

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
