### ISSUE TITLE
Remove Dashboard Link as Label if there is no dashboard for a following stage

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#376]
Scenario is the following
if you have a 2 stage delivery pipeline, e.g: staging and prod and use a Dynatrace Dashboard for SLOs for staging but not for prod the following happens
1: the Dynatrace-SLI-Service will add the link to the dashboard as a label on the `sh.keptn.internal.event.get-sli.done` event for staging
2: the label will make it all the way to production and will not be cleared by the next 'sh.keptn.internal.event.get-sli.done' that is sent for production.

Now - this is something that the dynatrace-sli-service can "workaround" by clearing an old label - but - it also brings up a bigger question on labels and the "lifetime" of labels and metadata. Whether labels should be e.g: cleared when a process finishes at one stage or not!

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
