### ISSUE TITLE
Add Error Budget from Dynatrace SLO as SLI Metric

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#377]
For production deployments we should allow defining an SLI that is based on the current error budget of a Dynatrace SLI.
While we already support pulling in a Dynatrace SLO we are just pulling in the SLO Value itself, e.g: 98%.
What would be more interesting is to pull in the Error Budget and based on the availability of the Error Budget make a decision on deployment

So - if the Error Budget is negative then that should always fail the SLI
If the Error Budget is lets say < 1% then it might also still be too risky
If the Error Budget is > 1% then we might be good

I am therefore proposing a way to define an SLI that is based on Error Budget Value of a Dynatrace SLO.
the SLO in Keptn could then be e.g: pass >= 1%

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
