### ISSUE TITLE
Create Dynatrace Dashboard out of SLI & SLO.yaml

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#379]
This request is kind of the reverse from parsing a Dynatrace Dashboard and generate SLI & SLO

The request came from a user who asked for generating or updating the dashboard to visualize the defined SLI & SLOs in the YAMLs.
The logic could be like this
1: If no dashboard has been created before create a new one -> tag it with "project, stage, service" so we know this dashbaord was generated for that keptn project, stage & service
2: If dashboard exists add new SLIs as new charts -> just add it to the end of the dashboard as layouting can be done by the end users in the dashboard itself. It is really just about having all SLIs on the dashboard as separate charts

This implementation would need to parse the dashboard and ONLY ADD SLIs as new charts that havent been there before. Existing ONES should be left untouched. This also allows users in dynatrace to modify the layout as we would never be able to generate a dashboard to the layout likings of our users. If we however only add new SLIs to the dashboard and leave exisitng ones untouched we allow the user to do their own layouting

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
