### ISSUE TITLE
Provide a link from Keptn to Dynatrace Service Screen

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#383]
When synchronizing a Dynatrace Monitored Service with Keptn we get a new service in the dynatrace keptn project. This service comes with pre defined SLIs & SLOs. When running a quality gate it would be great to get a link back to the Service in Dynatrace or to the List of Services (Transaction & Services) in Dynatrace showing all the services that match the keptn_manged & keptn_service:SERVICENAME filter

This would then be a great two-way integration

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
