### ISSUE TITLE
Improve error handling for dashboard SLIs that dont return a value

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#387]
Currently if getting data from the Dynatrace dashboard doesnt return any SLI results, for example because the SLI is currently unavailabe, SLIs are queried based on SLI.yaml definitions resulting in an error.  Instead, users should be informed that there was simply no data returned.

The main logic for the SLI processing is here:

https://github.com/keptn-contrib/dynatrace-sli-service/blob/1eab1d8a023e9120d9791cdc6c4e74d2f5463fdb/cmd/main.go#L290-L468

**Comment by Kavindu-Dodan** [comment]
Already done - #413
