### ISSUE TITLE
Refactoring: Several functions have become way too complex

### ISSUE THREAD

**Issue by bacherfl** [keptn-contrib/dynatrace-service#391]
Currently, there are a number of functions that have become too complex to maintain.
For example, the function ` QueryDynatraceDashboardForSLIs()` has six return values and is almost 300 lines long: 

https://github.com/keptn-contrib/dynatrace-sli-service/blob/3d9241b99a51177e5731765d373c35b858fade47/pkg/lib/dynatrace/dynatrace.go#L1548

Another example is the `GenerateSLISLOFromMetricsAPIQuery()` function with 15 input parameters: 
https://github.com/keptn-contrib/dynatrace-sli-service/blob/3d9241b99a51177e5731765d373c35b858fade47/pkg/lib/dynatrace/dynatrace.go#L1426

These are just two examples, but the situation is similar for a number of functions in https://github.com/keptn-contrib/dynatrace-sli-service/blob/3d9241b99a51177e5731765d373c35b858fade47/pkg/lib/dynatrace/dynatrace.go 

The aim of this task is to go through these functions, and check how they can be simplified, e.g. by defining dedicated structs that contain the parameters/return values of those functions, breaking their functionality up into smaller, more digestible functions.

**Comment by agrimmer** [comment]
Duplicate of https://github.com/keptn-contrib/dynatrace-service/issues/412, hence I am closing this issue.
