### ISSUE TITLE
Proper support for Data Explorer charts when using Dynatrace Dashboards

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#396]
Starting with Dynatrace 222 the Data Explorer will go GA and replace the current "Custom Chart". This means that over the next couple of months Dynatrace users will migrate their existing dashboards to the new data explorer and new dashboards will only contain data explorer charts. this is why the dynatrace-sli-service needs to provide proper support for the data explorer widget.

While there is support right now it contains several bugs. The workaround is to not use the dashboard approach but use the generated metric query code from the data explorer and put it into a sli.yaml. The dashboard approach however is much more user friendly which is why proper support is needed

I created a default dashboard that matches the dashboard we used to provide in the past in tutorials but now converted to use the data explorer. This dashboard should result in the same result as the prevoius dashboard

![image](https://user-images.githubusercontent.com/675886/122937246-1bbc7480-d372-11eb-81bb-1b16639a70aa.png)

Currently there are a couple of issues that I found so far, e.g:
* percentiles are currently not supported
* generated query contains the merge() directive
* filtering and splitting of dimensions is not supported properly

Here is a zipped version of the dashboard.json used.
[KQG;project=dynatrace;service=etfrontend;stage=quality-gate.zip](https://github.com/keptn-contrib/dynatrace-sli-service/files/6694768/KQG.project.dynatrace.service.etfrontend.stage.quality-gate.zip)

**Comment by Dynatrace-Adam-Gardner** [comment]
Commenting for attention on this issue. I created a custom service metric then charted it using data explorer tile to get the 90th percentile:

```
calc:service.my.service.metric:merge(dt.entity.service):percentile(90)
```
Dashboard tile title is:
```
my metric;sli=my_metric
```

But the `get-sli.finished` event shows this:

```
...
{
          "message": "Dynatrace API returned status code 400: Failed to parse selector: unexpected colon expecting key package component or namespace, consider adding double quotes around whitespace and special characters such as (): when these are meant literally, e.g. on the right side of a filter matcher. Example: \":\"., near 1-based column range [1,2).",
          "metric": "my_metric",
          "success": false,
          "value": 0
}
...
```

**Comment by drqc** [comment]
Hi I have more info about this requirement specifically the filter support https://github.com/keptn-contrib/dynatrace-service/issues/814

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
