### ISSUE TITLE
Not all Dynatrace Problem Details from Payload are forwarded to Keptn Problem Event

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#402]
When setting up the Notification integration in Dynatrace to send problem events to Keptn the user has a lot of fields available in Dynatrace to pass on to the external tool, e.g: Keptn

Here is a screenshot of such a notification integration showing the fields such as ProblemTitle, ProblemURL or ProblemDetailsHTML
![image](https://user-images.githubusercontent.com/675886/125576654-a2f65619-f3ff-4663-9910-36ca7c593775.png)

In the current implementation the dynatrace-service only seems to pass certain fields on to the new problem event. You can see this in problem_handler.go:121 in function handleOpenedProblemFromDT:
```
	newProblemData := keptn.ProblemEventData{
		State:          "OPEN",
		PID:            dtProblemEvent.PID,
		ProblemID:      dtProblemEvent.ProblemID,
		ProblemTitle:   dtProblemEvent.ProblemTitle,
		ProblemDetails: json.RawMessage(problemDetailsString),
		ProblemURL:     dtProblemEvent.ProblemURL,
		ImpactedEntity: dtProblemEvent.ImpactedEntity,
		Tags:           dtProblemEvent.Tags,
		Project:        project,
		Stage:          stage,
		Service:        service,
	}
```

This limits Dynatrace users to pass additional information to Keptn and then to the different Keptn Services that participate in the remediation workflow

Dynatrace-sli service should be able to forward any custom fields to the Keptn problem open event. This is required for some advanced auto-remediation use cases

**Comment by SaveethaRavi** [comment]
Hi team,

Any update on the above mentioned change in keptn ?

Regards,
Saveetha.R

**Comment by SaveethaRavi** [comment]
Hi team,

Any update on this change. Please let us know.

Regards,
Saveetha.R

**Comment by arthurpitman** [comment]
Hi @SaveethaRavi, just to clarify: for your use case, would adding forwarding for `ProblemDetailsHtml`, `ProblemDetailsText`, `ProblemImpact` and `ProblemSeverity` be sufficient?

@grabnerandi: While adding support for forwarding all details may require a significant change, I think at least these could be added in the meantime.

**Comment by SaveethaRavi** [comment]
Hi ,

We need the fields which highlighted in Yellow in the above screenshot.

Regards,
Saveetha.R

**Comment by SaveethaRavi** [comment]
Hi,

Could you please provide us the ETA for this enhancement to get complete? I need to provide the details to my manager.

Regards,
Saveetha.R

**Comment by arthurpitman** [comment]
Hi @SaveethaRavi, this will be added this week. If the next release isn't this week, we will provide you with a pre-release.

**Comment by SaveethaRavi** [comment]
Hi Arthur,

Thanks and waiting for your next updates.

Regards,
Saveetha.R

**Comment by SaveethaRavi** [comment]
Hi Arthur,

Any updates on the changes?

Regards,
Saveetha.R

**Comment by SaveethaRavi** [comment]
Hello Arthur,

Please let me know the status on this change as I want to give the same here.

Regards,
Saveetha.R

**Comment by johannes-b** [comment]
Hello @SaveethaRavi 

unfortunately, refactoring of the dynatrace-service and the merge with the dynatrace-sli-service has taken longer than expected. 
Nevertheless, this issue will be addressed this week meaning that you get a deployable service on the master branch by the end of this week.

**Comment by SaveethaRavi** [comment]
Thanks for the update.
