### ISSUE TITLE
Missing error logs when Dynatrace API not reachable or token is wrong

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#403]
Currently there is no error logging of the dynatrace-service when e.g: the Dynatrace API Endpoint is not reachable or the API token doesnt have the right priviliges.
The problem with this is that a user doesnt know, e.g: WHY Synchronization doesnt work

This should be an error that is logged as part of the error events

**Comment by arthurpitman** [comment]
First idea: The service could check that the Dynatrace credentials are valid by calling `/apiTokens/lookup` endpoint as part of the centralized configuration code. This end point also returns the scopes of the token which could then be examined by each use case of the service.

This issue could be addressed as part of changes for #426

**Comment by j-poecher** [comment]
implemented by improved error handling
