### ISSUE TITLE
Add missing screenshot on the configuration readme

### ISSUE THREAD

**Issue by robertjahn** [keptn-contrib/dynatrace-service#405]
On this page, there is a missing screenshot for the `keptn_managed` example
https://github.com/keptn-contrib/dynatrace-service/blob/master/documentation/configuration.md

Please see this section....
![image](https://user-images.githubusercontent.com/24907089/125826588-900f44c2-bec4-465c-b361-8af3f4b6c323.png)

**Comment by arthurpitman** [comment]
Closed by #409
