### ISSUE TITLE
No error log when sli.yaml is invalid - instead uses default slis

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#413]
Currently when defining an invalid SLI.yaml there is no error message that is presented to the user that there is a problem with the SLI. 
Here is an example of an sli.yaml one of our colleagues created - it is invalid because the quotes within the query should be escaped
```
---
spec_version: '1.0'
indicators:
  response_time_p95: "metricSelector=builtin:service.response.time:merge("dt.entity.service"):percentile(95)&entitySelector=type(SERVICE),tag(keptn_managed),tag(keptn_service:items)"
```

Here is the correct version of that sli.yaml.
```
---
spec_version: '1.0'
indicators:
  response_time_p95: "metricSelector=builtin:service.response.time:merge(\"dt.entity.service\"):percentile(95)&entitySelector=type(SERVICE),tag(keptn_managed),tag(keptn_service:items)"
```

The problem right now is that there is no indication that the sli.yaml couldnt be parsed. The current behavior is that the dynatrace-service falls back to the default sli's and the default queries.

**Comment by Kavindu-Dodan** [comment]
**DOD**

- Remove the fallback if user defined SLI definition is invalid, so we will have a consistent behavior  
- Proper error message in the event when this occur
