### ISSUE TITLE
Dashboard parsing should not allow multiple SLIs with the same name

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#441]
Currently dashboard parsing can create multiple SLIs with the same name. This can occur in the following circumstances:
- If different tiles of a dashboard have the same SLI name,
- If one tile produces multiple SLIs by appending entity names and the entities have the same name 
- If one tile has multiple queries or series and thus produces multiple SLIs (see #536)

*Versions*
- Dynatrace-service version 0.17.1

*Desired Behavior*
The dynatrace-service should abort dashboard parsing and produce an error.

**Comment by agrimmer** [comment]
Classification: Preventive

**Comment by arthurpitman** [comment]
Closed by #969
