### ISSUE TITLE
Feature Request: Customize Trusted CA Certificates

### ISSUE THREAD

**Issue by lmmarsano** [keptn-contrib/dynatrace-service#458]
Enterprises often have internal PKIs.
Rather than disable TLS checks,
https://github.com/keptn-contrib/dynatrace-service/blob/2803bdfab2cf5a4e1f2648ddf153a4fe0146b150/documentation/installation.md#L75
could we provide additional signing certificates to trust perhaps as ConfigMaps?

**Comment by arthurpitman** [comment]
Hi @lmmarsano, thank you for the suggestion, we will consider adding this in the future

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
