### ISSUE TITLE
Deployment Image and Tag of Deployment.Finished event do not consider root Image field of Deployment.Triggered event

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#469]
`DeploymentFinishedAdapter` provides `image` and `tag` by retrieving and looking at the associated `deployment.triggered` event.
Once it has retrieved the `deployment.triggered` event, the current implementation of `DeploymentFinishedAdapter.getImageAndTag()` only considers the `image` field inside `configurationChange` and does not fall back to the root `image` field if `configurationChange` is not present.

#### Image and Tag retrieved from `configurationChange` of `deployment.triggered` event:
1. Use /api/v1/event endpoint of Keptn API to forward the following `deployment.triggered` event:
```
{
    "data": {
        "configurationChange": {
            "values": {
                "image": "app:0.0.1"
            }
        },
        "image": "app:0.0.1",
        "message": "",
        "project": "platform",
        "result": "pass",
        "service": "app-gateway",
        "stage": "sandbox",
        "status": "succeeded"
    },
    "source": "shipyard-controller",
    "type": "sh.keptn.event.deployment.triggered",
    "shkeptncontext":  "d3639c64-26a9-4cda-a2b8-1be4f340777a"
}
```

2. Use /api/v1/event endpoint of Keptn API to forward the following `deployment.finished` event:
```
{
    "data": {
        "project": "platform",
        "service": "app-gateway",
        "stage": "sandbox"
    },
    "source": "shipyard-controller",
    "type": "sh.keptn.event.deployment.finished",
    "shkeptncontext":  "d3639c64-26a9-4cda-a2b8-1be4f340777a"
}
```
3. Observe `Image` and `Tag` correctly set in `DeploymentEvent`

#### Image and Tag not retrieved from root `image` of `deployment.triggered` event:
1. Use /api/v1/event endpoint of Keptn API to forward the following `deployment.triggered` event:
```
{
    "data": {
        "image": "app:0.0.1",
        "message": "",
        "project": "platform",
        "result": "pass",
        "service": "app-gateway",
        "stage": "sandbox",
        "status": "succeeded"
    },
    "source": "shipyard-controller",
    "type": "sh.keptn.event.deployment.triggered",
    "shkeptncontext": "6c14376b-2b50-4d7e-a28a-0fb5b3ab09e3"
 }
```

2. Use /api/v1/event endpoint of Keptn API to forward the following `deployment.finished` event:
```
 {
    "data": {
        "project": "platform",
        "service": "app-gateway",
        "stage": "sandbox"
    },
    "source": "shipyard-controller",
    "type": "sh.keptn.event.deployment.finished",
    "shkeptncontext":  "6c14376b-2b50-4d7e-a28a-0fb5b3ab09e3"
}
```
3. Observe `Image` and `Tag` incorrectly set to `n/a` in `DeploymentEvent`

### Proposed change
1. Add `Image` field to `v0_2_0.DeploymentTriggeredData` in `/pkg/lib/v0_2_0/deployment.go` in `keptn/go-utils` 
2. Add fallback behavior to use `Image` if no `ConfigurationChange` present in `DeploymentFinishedAdapter.getImageAndTag()` in `internal/deployment/deploymentfinished_adapter.go`.

**Comment by agrimmer** [comment]
According to the spec of the deployment.triggered event (https://github.com/keptn/spec/blob/master/cloudevents.md#deployment-triggered), the image information is in the `configruationChange` object. 
The triggered event which contains the image directly in the `data` object (your second example), is not an event which conforms to the Keptn spec and, hence, the dynatrace-service does not have to understand it.

**Comment by Kavindu-Dodan** [comment]
Closing as this request does not confirm to Keptn spec.
