### ISSUE TITLE
Dashboard were not created when configure monitoring with version 0.16.0

### ISSUE THREAD

**Issue by heckelmann** [keptn-contrib/dynatrace-service#477]
Hi,

when running through the tutorial (full tour of Dynatrace) the dashboards were not created by the dynatrace-service (https://deploy-preview-183--keptn-tutorials.netlify.app/tutorials/keptn-full-tour-dynatrace-09/index.html?index=..%2F..index#16)

Within the tutorial I was using as ENV Var without a prefix and the secret is created as well without https in front
![image](https://user-images.githubusercontent.com/89777493/132845946-0a38bd21-cfd8-4194-b326-dc5ba42bfe4d.png)

Please not the wrong URL (https://https://tenant)

![image](https://user-images.githubusercontent.com/89777493/132845640-ae95051c-0d4e-462d-84d5-6f946eea8241.png)

There is no error in the log
```
time="2021-09-10T10:51:08Z" level=info msg="Creating Dashboard for project" project=sockshop
time="2021-09-10T10:51:09Z" level=info msg="Dynatrace dashboard created successfully" dashboardUrl="https://https://frj61836.dev.dynatracelabs.com/#dashboards"
```
[dynatrace-service.log](https://github.com/keptn-contrib/dynatrace-service/files/7143413/dynatrace-service.log)

**Comment by j-poecher** [comment]
this has been fixed by #496
