### ISSUE TITLE
Security Hardening: Remove the role which allows to get, list, watch all secrets

### ISSUE THREAD

**Issue by agrimmer** [keptn-contrib/dynatrace-service#485]
The dyantrace-service has a Role that allows to get, list, and watch all secrets in the namespace where it is running.
See https://github.com/keptn-contrib/dynatrace-service/blob/master/chart/templates/serviceaccount.yaml

As an operator of the dynatrace-service, I would like have that the dynatrace-service only can access only those secrets which contain dynatrace tokens.

**Implementation details:**
- User has to use Keptn's secret-service with the scope "dynatrace-service" for managing secrets (see https://github.com/keptn/enhancement-proposals/pull/61) 
- Remove the role and rolebinding from the Helm chart

**DoD:**
- The documentation explains that either all secrets used by the dynatrace-service has to be recreated using the secret-service or how to manually add Roles and RoleBindings, which then allow reading the required secrets
- Dynatrace-service can only access secrets that contain Dynatrace tenant and API token information

**Comment by arthurpitman** [comment]
Closed by #524
