### ISSUE TITLE
Metric queries produced by parsing Data Explorer tiles should match code produced in the Dynatrace UI Data Explorer code tab.

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#502]
Metric queries produced by parsing Data Explorer tiles should match code produced in the Data Explorer code tab.

Currently this is not the case as the query is set up to aid decomposing it into individual SLIs depending on the result of the query. 
Instead, ideally the results of any query would be analyzed and produce multiple SLIs if it makes sense to do so.

Aiming to generate identical metric queries would aid in testing as then the Data Explorer code tab could be used as ground truth, important as as the dynatrace-service's ability to parse Data Explorer tiles improves. 

This issue overlaps with #396, #487 and #398

**Comment by Dynatrace-Adam-Gardner** [comment]
I've started work in a related area: https://github.com/Dynatrace-Adam-Gardner/dt-dataexplorer-to-dashboard-converter

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
