### ISSUE TITLE
Remove hardcoded default SLI definitions 

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#518]
**Current situation**
Right now the dynatrace-service always offers default SLIs even if none are derived from a dashboard or specified in the associated `sli.yaml`. 

**Describe the solution you'd like**
When services are onboarded or monitoring is configured for a project, a default `sli.yaml` is created together with a default `dynatrace.conf.yaml` via the configuration service, making the configuration completely clear to the user at any given point in time (via the project's git repository)

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
