### ISSUE TITLE
Create Problems on Failed Sequences

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn-contrib/dynatrace-service#547]
Keptn sequences failing could be serious enough that a Dynatrace user would want proactive alerts.

**Describe the solution you'd like**
Add the option to allow the `dynatrace-service` to create problem records in Dynatrace whenever a sequence fails (where the user has opted in for problem creation for that sequence, on that service, in that environment).

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
