### ISSUE TITLE
Keptn credentials should only be read from environment variables

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#557]
Currently the dynatrace-service attempts to read Keptn credentials (`KEPTN_API_URL`, `KEPTN_API_TOKEN` and optionally `KEPTN_BRIDGE_URL`) from a secret named `dynatrace`, falling back to environment variables if a value is not available.

However, users are encouraged to set `KEPTN_API_URL` and `KEPTN_BRIDGE_URL` during installation;  `KEPTN_API_TOKEN` is set from `keptn-api-token` secret. Thus reading credentials from the `dynatrace` secret should be discontinued.  

Users who still need the entire credentials to be read from a secret would still be able to modify the helm chart to reference a secret.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
