### ISSUE TITLE
Support for `/securityProblems` endpoint

### ISSUE THREAD

**Issue by kristofre** [keptn-contrib/dynatrace-service#572]
**Describe the solution you'd like**
Leveraging Dynatrace AppSec capabilities for quality gate evaluations means that users can detect vulnerabilities earlier in the development lifecycle and eventually stop them from being promoted to production environments.

Support for the `/securityProblems` endpoint should be through the dashboard approach and also to be defined in the sli.yaml specification.

**Comment by arthurpitman** [comment]
Currently the dynatrace-service supports retrieving security problem counts via the security problems endpoint in two ways:
- In the SLI file you can query the total problem count with the `SECPV2` prefix. The format should be `SECPV2;securityProblemSelector=selector`
- In the dashboard, open security problem count will be retrieved automatically if you add the problems tile (as there is currently no security problems tile). In this instance the SLI will be named `security_problems`

I have created #573 to handle the short comings and documentation of the existing support.

@kristofre, I will close this issue but feel free to reopen it if you need support beyond what is currently offered.
