### ISSUE TITLE
Graph-based queries are being combined incorrectly

### ISSUE THREAD

**Issue by eugenbelsky** [keptn-contrib/dynatrace-service#586]
As we discovered together with @arthurpitman, graph-based queries are being combined incorrectly ( management id related ). Therefore all the graph-based evaluations do not work. Here is the sample:
`Dynatrace API error (400): Metric selector parse error: line 1:161 extraneous input '(' expecting {<EOF>, COMMA}  - URL: https://gmg80500.dev.dynatracelabs.com/api/v2/metrics/query?from=1636990726000&metricSelector=builtin%3Aapps.other.requestCount.osAndProvider%3Amerge%28%22Provider%22%29%3Amerge%28%22Provider+Type%22%29%3Amerge%28%22dt.entity.os%22%29%3Amerge%28%22dt.entity.device_application%22%29%3Aavg%3Anames%2CmzId%282536143319290108719%29&resolution=Inf&to=1636990731000; Dynatrace API error (400): Metric selector parse error: line 1:122 extraneous input '(' expecting {<EOF>, COMMA}  - URL: https://gmg80500.dev.dynatracelabs.com/api/v2/metrics/query?from=1636990726000&metricSelector=builtin%3Aapps.other.sessionCount.osAndVersion-std%3Amerge%28%22App+Version%22%29%3Amerge%28%22dt.entity.device_application%22%29%3Aavg%3Anames%2CmzId%282536143319290108719%29&resolution=Inf&to=1636990731000`

**Comment by arthurpitman** [comment]
This is an example of what was reported in #425

**Comment by arthurpitman** [comment]
This issue was investigated in #599 and fixed in #600.
