### ISSUE TITLE
Dynatrace-service serviceAccount value defaults to release-name 

### ISSUE THREAD

**Issue by eugenbelsky** [keptn-contrib/dynatrace-service#587]
Dynatrace-service serviceAccount value defaults to release-name - which means the keptn secret will not work unless the release name is dynatrace-service since RoleBinding is always using dynatrace-service sa as a subject.

**Comment by arthurpitman** [comment]
This can be addressed with two action items:
- set default service account name to `dynatrace-service`
- update installation documentation to indicate that the dynatrace-service should be installed with release name of `dynatrace-service`

**Comment by Kavindu-Dodan** [comment]
@eugenbelsky  thank you for highlighting this issue. We will work on a fix and include this in the next release

@arthurpitman  I would recommend to make service name fixed to ```dynatrace-service```
