### ISSUE TITLE
Update default SLIs and examples to use `splitBy` rather than `merge`

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#589]
Currently the default SLIs of the dynatrace-service use `merge` and have the form:

```
throughput: metricSelector=builtin:service.requestCount.total:merge("dt.entity.service"):sum...
error_rate: metricSelector=builtin:service.errors.total.rate:merge("dt.entity.service"):avg..
response_time_p50: metricSelector=builtin:service.response.time:merge("dt.entity.service"):percentile(50)..
response_time_p90: metricSelector=builtin:service.response.time:merge("dt.entity.service"):percentile(90)..
response_time_p95: metricSelector=builtin:service.response.time:merge("dt.entity.service"):percentile(95)..
```

To produce metrics queries similar to the Data Explorer, these should be updated to use `splitBy`, i.e.:

```
throughput: metricSelector=builtin:service.requestCount.total:splitBy():sum...
error_rate: metricSelector=builtin:service.errors.total.rate:splitBy():avg...
response_time_p50: metricSelector=builtin:service.response.time:splitBy():percentile(50)...
response_time_p90: metricSelector=builtin:service.response.time:splitBy():percentile(90)...
response_time_p95: metricSelector=builtin:service.response.time:splitBy():percentile(95)...
```

This syntax also has the advantage of being more explicit and often more compact.

While the metrics queries produced when processing Data Explorer and Custom Charting tiles (#578), the following need updating:
- Default SLIs generated when onboarding services 
- SLIs in documentation
  - https://github.com/keptn-contrib/dynatrace-service
  - https://keptn.sh/docs/0.10.x/monitoring/dynatrace/configure_slis/
- Examples: https://github.com/keptn/examples
- Full tour: https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace-09/index.html?index=..%2F..index#16

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
