### ISSUE TITLE
SECPV2 should support placeholders

### ISSUE THREAD

**Issue by kristofre** [keptn-contrib/dynatrace-service#601]
**Describe the solution you'd like**
For the metrics v2 API it is possible to use dynamic `$LABEL.xxx` placeholders which are processed when performing an evaluation. For `SECPV2` this is not done. It would be great to allow that as well for the security problems endpoints.

**Comment by kristofre** [comment]
For example, standard metrics allow this format:
```
pg_heap_suspension:  "metricSelector=builtin:tech.jvm.memory.gc.suspensionTime:merge(\"dt.entity.process_group_instance\"):max&entitySelector=tag([ENVIRONMENT]DT_APPLICATION_RELEASE_VERSION:$LABEL.DT_APPLICATION_RELEASE_VERSION),tag([ENVIRONMENT]DT_APPLICATION_BUILD_VERSION:$LABEL.DT_APPLICATION_BUILD_VERSION),tag([ENVIRONMENT]DT_APPLICATION_ENVIRONMENT:$LABEL.DT_APPLICATION_ENVIRONMENT),tag([ENVIRONMENT]DT_APPLICATION_NAME:$LABEL.DT_APPLICATION_NAME),type(PROCESS_GROUP_INSTANCE)"
```

This would be translated by the dynatrace-service and keptn specific information (project, service, stage, ...) and custom labels would be inserted in lieu of the placeholders.

For the `SECPV2` endpoint this does not work:
```
app_sec_high:        "SECPV2;securityProblemSelector=pgiTags(\"[Environment]DT_APPLICATION_BUILD_VERSION:$LABEL.DT_APPLICATION_BUILD_VERSION\"),pgiTags(\"[Environment]DT_APPLICATION_RELEASE_VERSION:$LABEL.DT_APPLICATION_RELEASE_VERSION\")"
```
The above would not be translated and the original values remain.

If the above would be implemented, it would allow us to fetch vulnerabilities for specific Process Group Instances and dynamically evaluate them inside a quality gate.

**Comment by agrimmer** [comment]
Hi @kristofre,
thank you for the enhancement proposal.
You are right, we do not support placeholders for SLIs targeting security problems.
Before introducing such placeholders, I would like to double-check if the search&replace method which we are currently using for metrics is really the most stable/most robust solution.

**Comment by kristofre** [comment]
Thanks @agrimmer , appreciate the feedback.
Do you have a timeline for conducting such research?

**Comment by Kavindu-Dodan** [comment]
@kristofre we discussed this in the team & we will take this into our next sprint

**Comment by kristofre** [comment]
@Kavindu-Dodan did this make it into the 0.20.0 release? I don't think it did but wanted to make sure. Thanks!

**Comment by arthurpitman** [comment]
@kristofre No it did not, but I am currently working on it.
