### ISSUE TITLE
`MarkdownTileProcessing` should produce errors for dashboard markdown tiles that have bad syntax

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#629]
**Describe the bug**
Currently if a markdown tile for specifying global SLO comparison and score options contains invalid syntax, no error is returned to the user; it is simply ignored.

**Versions**
* Dynatrace-service version: 0.18.1

**Expected behavior**
While the user could have other sorts of markdown tile on a dashboard, if a tile is considered for parsing and contains obviously bad syntax, then a message should be returned to the user. E.g. specifying: `kqg.compare.results=2 results` should produce an error.

**Comment by agrimmer** [comment]
Classification: Preventive
