### ISSUE TITLE
Update documentation to indicate which Dynatrace API token scopes are required for which functionalities

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#634]
**Describe the bug**
Right now, the documentation suggests creating a Dynatrace API token with a limited but standard set of scopes: 
- Read metrics
- Ingest metrics
- Read logs
- Read entities
- Read problems
- Access problem and event feed, metrics, and topology
- Read configuration
- Write configuration
- Capture request data  

While this will work for basic SLIs using the Metrics v2 API, SLIs targeting SLOs, USQL queries and security problems will require additional scopes. The documentation should be updates to reflect this, in particular which SLI types need which scopes. Furthermore, it includes some scopes that users don't automatically need.

**Versions**

* Dynatrace-service version: 0.18.1
* Dynatrace cluster version: 1.233.0.20211214-201628

**Expected behavior**
Users should be guided to assign only the scopes the need to the their Dynatrace API tokens. Error messages should be checked to ensure they guide the user to the problem if their token is missing scopes.

**Additional context**
The default scopes suggested in the documentation should be reevaluated

**Comment by arthurpitman** [comment]
In #701:
- [`dynatrace-api-token-scopes.md`](https://github.com/keptn-contrib/dynatrace-service/blob/master/documentation/dynatrace-api-token-scopes.md) has been added specifying with API token scopes are required for which functionality.
- The default scopes described in [`project-setup.md`](https://github.com/keptn-contrib/dynatrace-service/blob/master/documentation/project-setup.md) enable all functionality. Scopes which are not currently needed have been removed.

Open tasks:
- Check that error messages guide the user to the problem if their token is missing scopes.

**Comment by j-poecher** [comment]
I guess we can close this as well @arthurpitman ?
