### ISSUE TITLE
All calls to Dynatrace APIs with timeframes should be delayed such that their timeframes ended at least two minutes previously

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#641]
**Describe the bug**
Currently the function `sli.ensureRightTimestamps(start string, end string)` delays execution for timeframes within two minutes only if their duration is less than 2 minutes and delays for one minute if their duration is less than 5 minutes:

https://github.com/keptn-contrib/dynatrace-service/blob/ab120e8373e03c8a5f2c7803c179ff6b7bfb71d7/internal/sli/get_sli_triggered_event_handler.go#L69-L116

**Versions**
* Dynatrace-service version : 0.18.1

**Expected behavior**
Instead, all calls to Dynatrace APIs with timeframes should be delayed such that their timeframes ended at least two minutes previously

**Comment by christian-kreuzberger-dtx** [comment]
This functionality was actually part of dynatrace-sli-service, but was removed at some point.

https://github.com/keptn-contrib/dynatrace-sli-service/blob/cce37f67bb3d26a75d7ea9e3fe23c4a835d725ee/cmd/main.go#L119-L136
