### ISSUE TITLE
Automatic onboard applications (frontend part of Dynatrace) using tags

### ISSUE THREAD

**Issue by drqc** [keptn-contrib/dynatrace-service#642]
Implement for front-end apps the same functionality that currently picks up services based on dynatrace tags (keptn_managed and keptn_service:servicename) and onboards these services into keptn for QG with some default metrics.

This would accelerate QG adoption. Some default metrics could be 
Visually complete 
Appdex 
Action duration
Page load

 
![image](https://user-images.githubusercontent.com/70604844/146815830-b4188eaa-cb4b-4979-985a-e301a7117a7b.png)

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
