### ISSUE TITLE
Misleading errors of dynatrace.conf.yaml not found when creating a new keptn project

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#657]
**Describe the bug**
With the changed behavior of mandating a dynatrace.conf.yaml we are receiving error messages that users havent received before even though there is no option to mitigate them. Thats why those error messages are misleading and I think not necessary
When creating a new keptn project the dynatrace-service handles the project.create.finished event. I am not sure what the dynatrace-service is doing when handling project.finished but right now it always throws an error that it cant find dynatrace.conf.yaml.

Here is a screenshot after I created 3 projects in my keptn
![image](https://user-images.githubusercontent.com/675886/147652145-cdf42306-8bf5-43a3-9da0-53ccdf80828d.png)

I think the dynatrace-service should only handle those events that actually cause an action. Plus - since the changed behavior of mandating the dynatrace.conf.yaml we should revisit when the dynatrace.conf.yaml is really needed and when not.

**Versions**

Versions of the applicable components

* Dynatrace Service version : 0.19.0
* Dynatrace cluster version : xx
* Keptn version: 0.11.4

**Comment by arthurpitman** [comment]
The dynatrace-service currently handles the `sh.keptn.event.project.create.finished` event by automatically configuring monitoring for the project:

https://github.com/keptn-contrib/dynatrace-service/blob/26a06d0b55da5ddad3290630f36fc6ef25ffa2dd/internal/monitoring/project_create_finished_event_handler.go#L29-L44

This is incorrect in my opinion, as until a `dynatrace/dynatrace.conf.yaml` file has been created the dynatrace-service can't communicate with the Dynatrace tenant. Furthermore, the dynatrace-service should not configure monitoring for a Keptn unless the user has explicitly asked for it.

As an interim solution, I would suggest removing this functionality.

**Comment by grabnerandi** [comment]
Agree with @arthurpitman on "removing this functionality" as there is no way for the user to define a dynatrace.conf.yaml at the time of project creation!
