### ISSUE TITLE
Misleading errors for keptn events on projects where dynatrace is not enabled

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#658]
**Describe the bug**
With the 0.19.0 change of mandating a dynatrace.conf.yaml there are a lot of new error messages we see. But - users also get error messages for events on projects that do not even have been configured for dynatrace. As an example look at the following screenshot. The devopstools keptn project doesnt use dynatrace - however - the dynatrace-service handles the deployment event and then throws an error about the missing dynatrace.conf.yaml

![image](https://user-images.githubusercontent.com/675886/147653420-51ae251b-9d6e-47ac-adf8-8759f775e8f0.png)

**Versions**

Versions of the applicable components

* Dynatrace Service version : 0.19.0
* Dynatrace cluster version : xxx
* Keptn version: 0.11.4

**To Reproduce**
Take any Keptn project and trigger a sequece that contains deployment or evaluation. you will see that error

**Expected behavior**
The dynatrace-service should only handle events for projects where dynatrace as enabled for monitoring. Not sure if there is a way for the dynatrace-service to know which projects it should handle or not - but - in the moment we are potentially creating a lot of error message the user cant do anything against except changing the event subscription on the dynatrace-service

**Comment by drqc** [comment]
I would add to that error more information. I says could not find resource even when the resource is uploaded to an specific stage (i.e. production, development). Had to run `keptn add-resource --project=easytravel --resource=./dynatrace.conf.yaml --resourceUri=dynatrace/dynatrace.conf.yaml`  removing `--stage=production`  to remove the error.

**Comment by arthurpitman** [comment]
@grabnerandi we have implemented #678 to make the error messages more actionable and will improve documentation in #682, asking users to modify their Keptn event subscriptions for projects where they do not the dynatrace-service to operate.

**Comment by Kavindu-Dodan** [comment]
Following issues are related, 

- https://github.com/keptn/keptn/issues/6627
https://github.com/keptn/keptn/issues/6628

**Comment by arthurpitman** [comment]
Furthermore we will encourage users to create and manage more granular subscriptions with #694.

**Comment by arthurpitman** [comment]
As we are now tracking #694 and #682, I will close this issue.
