### ISSUE TITLE
Sending too many Stop running tests events to Dynatrace

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#659]
**Describe the bug**
I have an keptn sequence containing a test task. I also have two testing tools (Jmeter and locust) sending started and finished events. In Dynatrace I however see 1 started and 3 finished events which dont make sense. See the screenshot of my bridge and then the screenshot of the dynatrace events

![image](https://user-images.githubusercontent.com/675886/147667904-e52039bb-c714-442d-a9d5-fdd87f424290.png)

![image](https://user-images.githubusercontent.com/675886/147667840-e1b9d7d7-4141-42c7-b57d-b2711528a118.png)

I assume the dynatrace-service currently sends the started event when the test sequence is triggered and it sends the stop event when the test tool sends a .finished. What I cant quite figure out is why I end up seeing 3 finished events in Dynatrace when there are only 2 finished events in the keptns bridge. 
Could be that the .changed event that locust sends is also handled as a finished which is in my opinion incorrect.

In general I think the behavior should be to send events for test.started and test.finished as this truly indicates when a test tool is picking up the task. It doesnt make sense to send an event when the task is triggered by the shipyard controller

**Versions**

Versions of the applicable components

* Dynatrace Service version : 0.19.0
* Dynatrace cluster version : xxx
* Keptn version: 0.11.4

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
