### ISSUE TITLE
Dynatrace service tags unrelated services

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/dynatrace-service#68]
**Problem:**
The automated tagging rules set up by the Dynatrace service tag unrelated services that are not being deployed by Keptn, as you can see in the screenshot

![image](https://user-images.githubusercontent.com/7677092/68497575-b9991500-0209-11ea-89b1-250080104390.png)

The service in the image has the tag "test-subject:true" but is not related to any tests performed by Keptn.

**Related** to https://github.com/keptn/keptn/issues/1025

**Desired state:**
Tag only services that have been deployed by Keptn.

**Comment by christian-kreuzberger-dtx** [comment]
This should no longer be the case with Keptn 0.6.0.beta and the latest version of the dynatrace-service
