### ISSUE TITLE
Use more neutral property names when sending events to Dynatrace

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#686]
Currently when sending events to Dynatrace property names such as Keptn Bridge, Keptn Service, ... are used.

![image](https://user-images.githubusercontent.com/675886/150340781-f9c18357-a5e0-449d-81ce-6410913f5df1.png)

As Dynatrace users may use Keptn or Cloud Automation (managed version of Keptn) it makes more sense to use labels that are more neutral

Here is a suggestion based on some internal discussions
Keptn Bridge -> Evaluation Details
Keptn Service -> Event Source
KeptnContext -> Sequence Context

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
