### ISSUE TITLE
Change default Keptn event subscription from wildcard to specifying the events the service is interested in

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#694]
**Is your feature request related to a problem? Please describe the problem.**
Currently, the dynatraces-service creates a default Keptn event subscription with wildcard - i.e. all events. This is difficult for the user to manage.

**Describe the solution you'd like**
Dynatrace-service should explicitly subscribe just to the individual events it is interested in.

**Comment by arthurpitman** [comment]
This can be achieved by adjusting the topics the distributor is configured to listen for, i.e. setting:
```
- name: PUBSUB_TOPIC
  value: 'sh.keptn.event.get-sli.triggered,sh.keptn.event.action.triggered,sh.keptn.event.action.started,sh.keptn.event.action.finished,sh.keptn.event.deployment.finished,sh.keptn.event.test.triggered,sh.keptn.event.test.finished,sh.keptn.event.evaluation.finished,sh.keptn.event.release.triggered,sh.keptn.event.release.finished,sh.keptn.events.problem,sh.keptn.event.monitoring.configure'
```
This produces the following individual subscriptions:
![individual_subscriptions](https://user-images.githubusercontent.com/2436759/151773136-42b0c678-b7dd-4138-8bbf-112e86f384f6.png)

While this makes it easy to remove subscriptions for events that no project should listen for, it does make it easier to apply these subscriptions to individual projects: this will require further improvements in the Keptn Bridge UI.

**Comment by Kavindu-Dodan** [comment]
As discussed, we will track the progress from Keptn core and adapt a solution later on.

**Comment by arthurpitman** [comment]
In particular, the progress of https://github.com/keptn/keptn/issues/5270 will be a prerequisite for this.
