### ISSUE TITLE
Remove support for legacy metrics queries

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#695]
Early in the life of the Dynatrace Environment v2 Metrics API, the endpoint was accessible `/metrics/series/{selector}?scope={scope}` where `{selector}` was essentially a metric selector and the optional `{scope}` was similar to an entity selector.

As a result, the dynatrace-service supported and still supports this `{selector}?scope={scope}` syntax for metrics queries.

The Dynatrace Metrics API endpoint was eventually changed and a log message was generated in the dynatrace-service indicating that users should update their queries to the current syntax. Further details were added to the dynatrace-sli-service in a help document titled `March 2020 Format Migration`:

https://github.com/keptn-contrib/dynatrace-sli-service/blob/master/docs/CustomQueryFormatMigration.md

**Describe the solution you'd like**
Now two years later, support for legacy metrics queries should be removed.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
