### ISSUE TITLE
Parsing Problem Tile in SLO Dashboard should not query Security Problems as well

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#722]
**Describe the bug**
Right now when adding a Problem Tile to a dashboard that is used as an evaluation dashboard the implementation queries both the open problems (via problem api) as well as the open security problems (via security problems API).
This was initially implemented to support the Security Use Case in an easier way. As time has passed the Security Quality Gate use case can be implemented by simply using the Security Metrics or by using the sli.yaml approach of defining security queries.

The problem with the current approach is that Dynatrace users that add the Problem tile to their dashboard will get an error in case they have not yet purchased AppSec. Its because AppSec introduces a new Permission Scope to access security problem details. If AppSec feature isnt enabled this scope is not availabe and can therefore not be set for the API token. The current dynatrace-service implementation will however run into an error which shows like this in the Keptns Bridge

![image](https://user-images.githubusercontent.com/675886/155972272-b502a19e-075e-4376-a964-80f283b081a5.png)

**Versions**

Versions of the applicable components

* Dynatrace Service version : 0.21.0
* Dynatrace cluster version : 235
* Keptn version: 0.13.1

**To Reproduce**
Create a dashboard with a Problem tile. then use that for an evaluation

**Expected behavior**
I think we should JUST query the problems API because this is what the user would expect!

**Comment by agrimmer** [comment]
Classification: Adaptive, behavior, breaking change
