### ISSUE TITLE
Shutdown gracefully in response to `SIGINT` and `SIGTERM` events

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#729]
**Is your feature request related to a problem? Please describe the problem.**
To support high availability, the dynatrace-service must support graceful shutdown.

**Describe the solution you'd like**
Once it receives `SIGINT` or `SIGTERM`, the dynatrace-service should begin to shutdown and no longer process new events. It should handle the termination signal by finishing its current tasks and cleaning up resources so that it can shut down gracefully rather than being killed by Kubernetes.

**Additional context**
Reference info and implementations are provided in keptn/keptn#4522

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
