### ISSUE TITLE
Configure Dynatrace Web UI Domain separately to Dynatrace API Endpoint

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#731]
**Is your feature request related to a problem? Please describe the problem.**
We have users where the Dynatrace API is exposed through a special gateway domain, e.g: https://gateway.mycompany.com/xxxx - however - the Dynatrace Web UI runs on the regulard Dynatrace Managed domain URL,e .g: https://mydynatrace.mycompany.com behind a firewall

Right now the dynatrace-service by default creates a dashboard link when queriying a dashboard that will be passed as a label in the get-sli.finished event. In my example above the link to that dashboard will point to the API gateway but is not a valid link to actually open up the Dynatrace dashboard -> leading to an HTTP 4xx for users

**Describe the solution you'd like**
A "workaround" that might not be possible is for our users to configure their gateway to redirect to the dynatrace web ui domain.
A better solution however would be to extend the dynatrace secret and additionally to API Endpoint and Token also specify a Dynatrae UI Domain that would be used to create any links back to the Dynatrace UI such as the dashboard.

**Comment by APMGitHub** [comment]
We are using cloud automation and this feature will greatly help our organization.
Thank you

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
