### ISSUE TITLE
Dashboard feature randomly uses `name` or `customName` to derive the SLI config

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-service#735]
### Setup

I have a Data Explorer tile on my Dynatrace dashboard that has both: `name` and `customName` set with the comma-separated SLI config:

![image](https://user-images.githubusercontent.com/729071/157673954-04b539fc-f086-47e2-b8ce-6c50c88c556e.png)

The raw tile config looks as follows. (Please note, the `customName` should be `Response time (P75);sli=svc_rt_p75...` to make the example correct. But this has no impact on the problem.)

```
{
  "name": "Response time (P75);sli=response_time_(p75);pass=<=100;warning=<=200;weight=2;key=true",
  "nameSize": "",
  "tileType": "DATA_EXPLORER",
  "configured": true,
  "bounds": {
    "top": 228,
    "left": 456,
    "width": 380,
    "height": 114
  },
  "tileFilter": {},
  "customName": "Response time (P90);sli=svc_rt_p90;pass=<+10%,<550",
  "queries": [
    {
      "id": "A",
      "metric": "builtin:service.response.time",
      "spaceAggregation": "PERCENTILE_75",
      "timeAggregation": "DEFAULT",
      "splitBy": [],
      "filterBy": {
        "nestedFilters": [],
        "criteria": []
      },
      "enabled": true
    }
  ],
  "visualConfig": {
    "type": "SINGLE_VALUE",
    "global": {
      "hideLegend": false
    },
    "rules": [
      {
        "matcher": "A:",
        "properties": {
          "color": "DEFAULT"
        },
        "seriesOverrides": []
      }
    ],
    "axes": {
      "xAxis": {
        "visible": true
      },
      "yAxes": []
    },
    "heatmapSettings": {},
    "singleValueSettings": {
      "showTrend": false,
      "showSparkLine": false,
      "linkTileColorToThreshold": true
    },
    "thresholds": [
      {
        "axisTarget": "LEFT",
        "rules": [
          {
            "value": 0,
            "color": "#7dc540"
          },
          {
            "value": 400000,
            "color": "#f5d30f"
          },
          {
            "value": 550000,
            "color": "#dc172a"
          }
        ],
        "queryId": "",
        "visible": true
      }
    ],
    "tableSettings": {
      "isThresholdBackgroundAppliedToCell": false
    },
    "graphChartSettings": {
      "connectNulls": false
    },
    "honeycombSettings": {}
  },
  "queriesSettings": {
    "resolution": ""
  }
},
```

### Execution 

When running a QG evaluation with Keptn, either the `customName` or the `name` is used for **all SLIs** to derive the SLI config (key, pass, warning, etc.). The weird thing is that this is random and follows no pattern. I have never changed the dashboard. Please see here: 

![image](https://user-images.githubusercontent.com/729071/157673489-c2f068ea-04c0-4dc3-9f10-a840bda37df6.png)

## Expected behaviour

* I would expect that the `name` is used when containing a SLI config
* If name has no SLI config, a fallback to `customName` is possible.

**Comment by johannes-b** [comment]
I changed this issue from a `bug` to a `feature request` because with the help of @arthurpitman I have figured out that another Dashboard was interfering here.

Another Dynatrace user created another DT-dasbhoard with the very same name: `KQG;project=sockshop;service=carts;stage=staging` 
As a result, this dashboard was sometimes used. (I assume depending on the order from the Dynatrace API response). 

### Feature request

* In case multiple dashboards are found that have the same name (or match the query: `KQG;...`), stop processing with a `result=fail` and inform the user `message=x dashboards with the same match criteria found in your tenant, match criteria are: ...; Further processing stopped`

**Comment by arthurpitman** [comment]
@johannes-b, I will close this as I've created to follow up issues #740 and 741 to address the points raised here
