### ISSUE TITLE
Return an explicit error message if no SLIs are requested when using SLIs from YAML files

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#746]
**Is your feature request related to a problem? Please describe the problem.**
A common problem when using SLIs and SLOs from YAML files is that no SLI results will be returned in a `sh.keptn.event.get-sli.finished` event if none are requested in the `sh.keptn.event.get-sli.triggered` event.

Currently this results in an error `"could not retrieve any SLI results"`, but this does not really describe the real problem.

**Describe the solution you'd like**
Explicitly catch this case earlier on and return a better message like `"no SLIs were requested"`.

A further point: should returning no SLI results lead to a `result="failed"` or would `"warning"` be a better fit?

**Comment by j-poecher** [comment]
I think this can be closed already @arthurpitman, right?

**Comment by arthurpitman** [comment]
Yes, that is right, it was addressed in #901, so let's close this
