### ISSUE TITLE
inconsistent documentation of dynatrace-service configuration

### ISSUE THREAD

**Issue by lmmarsano** [keptn-contrib/dynatrace-service#757]
I noticed this while attempting to prepare a validation schema.
Compare
https://github.com/keptn-contrib/dynatrace-service/blob/2adc84aadfcf32bd3b69aaed0471ddf919ab5e23/documentation/dynatrace-conf-yaml-file.md?plain=1#L12
https://github.com/keptn-contrib/dynatrace-service/blob/2adc84aadfcf32bd3b69aaed0471ddf919ab5e23/documentation/project-setup.md?plain=1#L71

If both spellings are supported, then please document that or provide a schema as keptn already does for

- [service level indicator](https://github.com/keptn/spec/blob/master/service_level_indicator.md#specification)
- [service level objective](https://github.com/keptn/spec/blob/master/service_level_objective.md#specification).

**Comment by arthurpitman** [comment]
Hi @lmmarsano, thank you for catching this, the correct one is `spec_version`.
