### ISSUE TITLE
Refactor and improve initialization of event handlers

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#785]
Currently the dynatrace-service requires that getting a `dynatrace/dynatrace.conf.yaml` config file and Dynatrace credentials succeed before processing any event, regardless of whether these are actually needed. On the other hand, Keptn credentials are documented as being required as [part of the installation](https://github.com/keptn-contrib/dynatrace-service/blob/15c1132c5fce01fb4391a2a2e19643aa3fa4e90a/documentation/installation.md#2-gather-keptn-credentials), but are technically not required for all events and are retrieved when needed.

This should be reexamined, striking the right balance between:
- Consistent behavior: the dynatrace-service's processing of events should be easy to understand --> Concise documentation
- Simplicity: the user should need to set up the minimum possible to get the functionality they need
- Concise code that is easy to test and maintain

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
