### ISSUE TITLE
[FEATURE] Metrics Ingest

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/dynatrace-service#786]
**Is your feature request related to a problem? Please describe the problem.**
Add ability for the Dynatrace service to ingest metrics using the line format.

**Describe the solution you'd like**
Imagine a JSON payload with a set of metric lines like this:

```
{
  "type": "sh.keptn.event.dynatrace.metrics.ingest.triggered",
  "data": {
    "metrics": [{
      "engine.capacity 1234"
    },{
      "engine.temperature 78"
    }, ...]
  }
}
```

The dynatrace-service would then use the `/api/v2/metrics/ingest` endpoint to ingest those metrics to Dynatrace.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
