### ISSUE TITLE
Refactor event adapters to include fields present in the actual events

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#788]
Currently the `adapter.EventContextAdapter` interface includes the methods for getting deployment, test strategy and deployment strategy: 

https://github.com/keptn-contrib/dynatrace-service/blob/479d2f22dc165c87beff19db4773aa78acb54617/internal/adapter/event_content_adapter.go#L12-L14

These may or may not be present in the actual event and thus should be removed from this more basic interface. Furthermore some events have conflicting fields, e.g. the `sh.keptn.event.deployment.finished` event has a `deployment` object which is not accessible at all through the `DeploymentFinishedAdapterInterface` interface.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
