### ISSUE TITLE
[FEATURE] Push deployment.triggered metrics to DT

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/dynatrace-service#796]
The dynatrace-service should listen for `deployment.triggered` events and push custom metrics when heard, split by project, service and stage and result.

This can be used to track deployment frequency on a Dynatrace dashboard.

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
