### ISSUE TITLE
Dynatrace service for keptn 0.14.1+: override distributor

### ISSUE THREAD

**Issue by kristofre** [keptn-contrib/dynatrace-service#797]
**Describe the bug**

On the readme it mentions the following statement:

* Note: to install dynatrace-service 0.22.0 for Keptn 0.14.1 or later, please override the bundled distributor version and target the appropriate Keptn version by setting the Helm chart variable distributor.image.tag, i.e. by appending --set distributor.image.tag=... during the Helm upgrade.

As it doesn't offer a value to set it to nor where to find applicable values, this is confusing for the end-user.

We should offer either/both a suggested version or a place where to find an applicable tag.

**Comment by arthurpitman** [comment]
Closing this issue as the distributor will no longer be included in future releases (see #803 for details)
