### ISSUE TITLE
Service crashes when Project "dynatrace" is not created

### ISSUE THREAD

**Issue by thschue** [keptn-contrib/dynatrace-service#805]
**Describe the bug**
The Dynatrace crashes when the Project Dynatrace is not available

**Versions**

Versions of the applicable components

* Dynatrace Service version : 0.22.0
* Keptn version: 0.14.2

**To Reproduce**
* Install Dynatrace Service on a Keptn environment without the "dynatrace" project

**Expected behavior**
* Service logs / notifies that the project is not available, starts to work when the project is created

**Current behavior**
* Service Crash-Loops
* Following error message appears in the logs
`time="2022-05-13T15:18:34Z" level=error msg="Could not establish Dynatrace API connection" error="failed to load Dynatrace config: could not find resource: 'dynatrace/dynatrace.conf.yaml' of project 'dynatrace'"`

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
