### ISSUE TITLE
Helm chart doesn't allow pulling images from private container registry

### ISSUE THREAD

**Issue by tobigremmer-dt** [keptn-contrib/dynatrace-service#809]
**Describe the bug**
Helm chart doesn't allow pulling images from private container registry.

```
...
Release "dynatrace-service" does not exist. Installing it now.
Error: values don't meet the specifications of the schema(s) in the following chart(s):
dynatrace-service:
- dynatraceService.image.repository: Does not match pattern '^[a-z0-9][a-z0-9-./]{0,511}$'
...
```

*dynatraceService.image.repository* has been specified as "nexus:5555/dynatrace-service". Regex pattern is missing ":".

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
