### ISSUE TITLE
Dashboard generated SLI with multiple filter tags

### ISSUE THREAD

**Issue by drqc** [keptn-contrib/dynatrace-service#814]
Using Dynatrace dashboard for SLI/SLO definition:
Currently when trying to use multiple tags as filters in a Dynatrace SLI/SLO dashboard I get the following error (in cloud Automation)

`data Explorer tile could not be converted to a metric query: only a single filter criterion is supported`

I'm building a use case where I need at least 2 tags to specify a service i.e. "app:simplenodeservice" "environment:staging" to have a working SLI/SLO definition. This is fairly easy to do in the yaml version but the requirement for this implementation is to use the dashboard approach.
The dashboard template that I'm currently using for reference

`
           {
            "dashboardMetadata": {
              "dashboardFilter": null,
              "name": "Sample quality gate",
              "owner": "diego.quispe@test.com",
              "shared": false,
              "tilesNameSize": null
            },
            "tiles": [
              {
              "bounds": {
                "height": 38,
                "left": 0,
                "top": 0,
                "width": 874
              },
              "configured": true,
              "markdown": "KQG.Total.Pass=90%;KQG.Total.Warning=75%;KQG.Compare.WithScore=pass;KQG.Compare.Results=1;KQG.Compare.Function=avg",
              "name": "Markdown",
              "nameSize": null,
              "tileFilter": {
                "managementZone": null,
                "timeframe": null
              },
              "tileType": "MARKDOWN"
              },
              {
              "bounds": {
                "height": 304,
                "left": 0,
                "top": 114,
                "width": 304
              },
              "configured": true,
              "customName": "Data explorer results",
              "name": "sli=response_time;pass=\u003c20",
              "nameSize": null,
              "queries": [
                {
                "enabled": true,
                "filterBy": {
                  "criteria": [],
                  "entityAttribute": null,
                  "filter": null,
                  "filterOperator": "AND",
                  "filterType": null,
                  "globalEntity": null,
                  "nestedFilters": [
                  {
                    "criteria": [
                    {
                      "evaluator": "IN",
                      "matchExactly": null,
                      "value": "app:simplenodeservice"
                    },
                     {
                      "evaluator": "IN",
                      "matchExactly": null,
                      "value": "environment:staging"
                    }
                    ],
                    "entityAttribute": null,
                    "filter": "dt.entity.service",
                    "filterOperator": "OR",
                    "filterType": "TAG",
                    "globalEntity": null,
                    "nestedFilters": []
                  }
                  ]
                },
                "foldTransformation": null,
                "id": "A",
                "limit": 100,
                "metric": "builtin:service.response.time",
                "metricSelector": null,
                "sortBy": "DESC",
                "spaceAggregation": "PERCENTILE_90",
                "splitBy": [],
                "timeAggregation": "DEFAULT"
                }
              ],
              "queriesSettings": {
                "foldAggregation": null,
                "foldTransformation": null,
                "resolution": ""
              },
              "tileFilter": {
                "managementZone": null,
                "timeframe": null
              },
              "tileType": "DATA_EXPLORER",
              "visualConfig": {
                "axes": {
                "xAxis": {
                  "displayName": "",
                  "visible": true
                },
                "yAxes": [
                  {
                  "defaultAxis": true,
                  "displayName": "",
                  "max": "AUTO",
                  "min": "AUTO",
                  "position": "LEFT",
                  "queryIds": [
                    "A"
                  ],
                  "visible": true
                  }
                ]
                },
                "global": {
                "hasTrendline": null,
                "hideLegend": false,
                "seriesType": null,
                "theme": null,
                "threshold": null
                },
                "graphChartSettings": {
                "connectNulls": false
                },
                "heatmapSettings": {
                "xAxisBuckets": null,
                "yAxis": "VALUE",
                "yAxisBuckets": null
                },
                "honeycombSettings": {
                "showHive": true,
                "showLabels": false,
                "showLegend": true
                },
                "rules": [
                {
                  "matcher": "A:",
                  "properties": {
                  "alias": null,
                  "color": "DEFAULT",
                  "seriesType": "LINE"
                  },
                  "seriesOverrides": [],
                  "unitTransform": "",
                  "valueFormat": "auto"
                }
                ],
                "singleValueSettings": null,
                "tableSettings": {
                "isThresholdBackgroundAppliedToCell": false
                },
                "thresholds": [
                {
                  "axisTarget": "LEFT",
                  "columnId": null,
                  "queryId": "",
                  "rules": [
                  {
                    "color": "#7dc540",
                    "value": null
                  },
                  {
                    "color": "#f5d30f",
                    "value": null
                  },
                  {
                    "color": "#dc172a",
                    "value": null
                  }
                  ],
                  "visible": true
                }
                ],
                "type": "GRAPH_CHART"
              }
              }
            ]
            }
`

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
