### ISSUE TITLE
SLO evaluation fails when comparing against value 0.

### ISSUE THREAD

**Issue by drqc** [keptn-contrib/dynatrace-service#818]
**Describe the bug**
When running a quality gate with a yaml definition and a return value of zero the keptn service fails when comparing a Value of 0 to 0. (as per the keptn bridge). I have tried increasing the percentage to more than 100% to check if it was a unit problem without success. 

expression being used:
sli.yaml  
`databaseCalls(total_in_timeframe): "metricSelector=builtin:service.dbChildCallCount:merge(\"dt.entity.service\")&entitySelector=tag("something"),type(SERVICE)"`

slo.yaml
`
              - sli:  databaseCalls(total_in_timeframe)
                pass:
                  - criteria:
                      - "<+101%" 
`

![image](https://user-images.githubusercontent.com/70604844/171067435-e6e5f3a1-c3aa-4343-8922-a778853ecea7.png)

This is a random behavior that might be related to the information being returned from Dynatrace since sometimes I'm getting successful values on the next run. This is currently a blocker to reliably use SLI definitions with zero value returns.

![image](https://user-images.githubusercontent.com/70604844/171067707-dc52b641-3f30-4549-a112-8f1aca3dc32b.png)

**Comment by j-poecher** [comment]
Hi @drqc thanks for bringing this up. Which versions are you using for **Keptn** and **dynatrace-service**?

**Comment by drqc** [comment]
I had the issue on keptn 0.14 and dynatrace-service 0.20 but I also saw the same issue on Cloud Automation a week ago with Josh Lange during an engagement

**Comment by j-poecher** [comment]
@thisthat maybe you can have a look here, too.

Thank you :slightly_smiling_face:

**Comment by thisthat** [comment]
Sure, I will have a look if this is a problem with the lighthouse-service!

**Comment by thisthat** [comment]
Hey @drqc,  I noticed that your criteria value is `<+101%`. Since you said the SLI value 0 is compared against the previous value 0, this results in checking `0 < 0` which is false. Hence, the evaluation fails. I would suggest changing the comparison to `<=` so that it does not fail in the case of 0 value comparison.

**Comment by drqc** [comment]
@thisthat not sure how the SLO would read in that case. `<=+101%`? For me, this would mean that an increase of 101% or more over the indicator would break the SLO objective and if I put `<+101%` this would be an increase over 101% (not including 101%) would break the SLO, but in both cases an increase lower than 100% should not break the SLO. (the unit is count of DB calls and the comparison that I'm trying to use is a relative increase between 2 evaluations)

**Comment by agrimmer** [comment]
What I understand (and please correct me if I am wrong):
We are trying to calculate relative changes but use 0 as the basis. The result will always be 0. 
Hence, the suggestion by @thisthat to change the comparison to `<=` seems to be correct.
However, if the number of DB calls starts with 0, the condition will only be true if the DB calls stay 0.
To fix this problem, you can for example add a second pass criteria which are combined using a logical OR:
pass:
  - criteria:
    - "<=+101%"
  - criteria:  
    - "<=1"

**Comment by drqc** [comment]
That should be the case but the behaviour is inconsistent. Take this example 
![image](https://user-images.githubusercontent.com/70604844/173625168-bbd09008-5474-42a4-8754-4e7ce2aff7d3.png)
Or this one, for the same service I'm getting 2 different results 
![image](https://user-images.githubusercontent.com/70604844/173625899-14517612-659e-4ed3-aa6e-fec268a21b31.png)
![image](https://user-images.githubusercontent.com/70604844/173626018-2644eb85-2ecf-4a34-b33b-d49652d7213d.png)

**Comment by drqc** [comment]
Also I added the values you provided for the SLO in a dashboard QG but it still fails 
![image](https://user-images.githubusercontent.com/70604844/173637140-8d966585-4a48-4857-9f14-38dc98db9c3e.png)

**Comment by agrimmer** [comment]
I was not able to detect any inconsistencies but please note:
* Formulate the condition as a logical OR (you have a logical AND):
```
  pass:
  - criteria:
    - "<=+101%"
  - criteria:  
    - "<=1"
```
Note the difference: I have two `criteria` defined. 

* If you configure the relative comparison as defined below in your slo.yaml, the comparison uses the last evaluation result where the overall result is a `pass`. But if no evaluation with result `pass` is available, no comparison can be executed and the result is `pass` by default. This explains the different results.
```
comparison:
  compare_with: single_result
  include_result_with_score: pass
  number_of_comparison_results: 1
  aggregate_function: avg
```

**Comment by j-poecher** [comment]
will close this issue, because an answer has been provided and as it has been stale for a while
