### ISSUE TITLE
Exchange Dynatrace Events v1 API with version 2 in events client

### ISSUE THREAD

**Issue by j-poecher** [keptn-contrib/dynatrace-service#823]
Currently the `EventsClient` is using Dynatrace API `/api/v1/events` endpoint, which is **deprecated**. 

Change the implementation to use `/api/v2/events` endpoint and data structures.

**Comment by lavakush07** [comment]
Hello @j-poecher Can I take this issue ?

**Comment by j-poecher** [comment]
Hi @lavakush07, thanks a lot for your interest in this project :+1: 

We are currently discussing this issue internally, as it is not that straight-forward and will have some side effects, that are not considered here yet.
This is also actually the last issue we will be working on for our LTS release that will be coming soon.

I will come back to you as soon as we have identified a good starter ticket for you, if that's OK?

**Comment by lavakush07** [comment]
Yeah @j-poecher it is completely fine 👍

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
