### ISSUE TITLE
Have some way to remove various Dynatrace configurations when uninstall keptn 

### ISSUE THREAD

**Issue by robertjahn** [keptn-contrib/dynatrace-service#86]
when I uninstall Keptn, we need some automated way to remove things like the notifications and tagging rules.  

Here is an example after several installs and uninstalls.
![image (3)](https://user-images.githubusercontent.com/24907089/71221724-ad3db880-229b-11ea-9f88-c4ba19556456.png)

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for bringing this up.

With version 0.6.x of the dynatrace-service, there are even more things to consider cleaning up:

* management zones
* dashboards
* tagging rules
* custom events

in the case of

* project deleted
* dynatrace-service uninstalled

**Comment by agrimmer** [comment]
This type of use case will be supported by Monaco (see #237 for details)
