### ISSUE TITLE
"Send test notification" in Dynatrace fails after running ./deployDynatraceOnGKE.sh 

### ISSUE THREAD

**Issue by avodaqstephan** [keptn-contrib/dynatrace-service#87]
Hi, 

I edited the ./deployDynatraceCommon.sh a little bit because I already had the Dynatrace Operator installed. The problem notification and dynatrace-service is installed successfully but when I send a test notification out of Dynatrace I'll get a HTTP 400.

![image](https://user-images.githubusercontent.com/58725083/71357790-1c125e80-2587-11ea-8376-c02bcbeda926.png)

Kind regards,
Stephan

**Comment by christian-kreuzberger-dtx** [comment]
I think this problem has been fixed with the release of version 0.6.x of the dynatrace-service. I'm closing this issue for now, please re-open it if it still exists.
